### ISSUE TITLE
Not getting face/object detection: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by JohanE67** [xemle/home-gallery#106]
I'm following the quickstart in the docs for Docker Compose install. Everything seems to work properly, apart from the face/object detection. In the logs, I'm seeing lines like the ones below:

[2023-12-18 16:04:53.487]: index Updated file index for directory /data/Photos
[2023-12-18 16:04:53.545]: cli.spawn Run cli with extract --index /data/config/Photos.idx --storage /data/storage --api-server http://home-gallery-api-server:3000 --api-server-timeout 30 --api-server-concurrent 5 --journal 1218-gBOK
[2023-12-18 16:05:00.378]: index.readStream Reading file index journal /data/config/Photos.idx.1218-gBOK.journal
[2023-12-18 16:05:01.870]: extractor.image.resize Use sharp to resize images
[2023-12-18 16:05:32.472]: extractor Processed 5 entries (#5, +5, processing 11 and queued 0 entries)
[2023-12-18 16:05:32.720]: extractor.apiEntry warn Could not get face detection of 348c242:Photos:Sponsor/20220910134336_IMG_2449.JPG from URL http://home-gallery-api-server:3000/faces: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.737]: extractor.apiEntry warn Could not get face detection of 848f93b:Photos:Sponsor/20220910134337_IMG_2450.JPG from URL http://home-gallery-api-server:3000/faces: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.741]: extractor.apiEntry warn Could not get face detection of 1168991:Photos:Sponsor/20220910134338_IMG_2451.JPG from URL http://home-gallery-api-server:3000/faces: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.745]: extractor.apiEntry warn Could not get object detection of 904b76c:Photos:Sponsor/20220910134338_IMG_2452.JPG from URL http://home-gallery-api-server:3000/objects: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.749]: extractor.apiEntry warn Could not get object detection of ffee249:Photos:Sponsor/20220910134353_IMG_2453.JPG from URL http://home-gallery-api-server:3000/objects: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.754]: extractor.apiEntry warn Could not get similarity embeddings of 559147c:Photos:Sponsor/20220910134406_IMG_2455.JPG from URL http://home-gallery-api-server:3000/embeddings: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.759]: extractor.apiEntry warn Could not get similarity embeddings of 3bc48a0:Photos:Sponsor/20220910134417_IMG_2456.JPG from URL http://home-gallery-api-server:3000/embeddings: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.763]: extractor.apiEntry warn Could not get object detection of ec94438:Photos:Sponsor/20220910134405_IMG_2454.JPG from URL http://home-gallery-api-server:3000/objects: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.771]: extractor.apiEntry warn Could not get similarity embeddings of 7cc7c38:Photos:Sponsor/20220910134423_IMG_2457.JPG from URL http://home-gallery-api-server:3000/embeddings: Error: ESOCKETTIMEDOUT
[2023-12-18 16:05:32.777]: extractor.apiEntry warn Could not get similarity embeddings of b1cc51a:Photos:Sponsor/20220910134426_IMG_2458.JPG from URL http://home-gallery-api-server:3000/embeddings: Error: ESOCKETTIMEDOUT
[2023-12-18 16:06:02.878]: extractor.apiEntry warn Could not get face detection of 904b76c:Photos:Sponsor/20220910134338_IMG_2452.JPG from URL http://home-gallery-api-server:3000/faces: Error: ESOCKETTIMEDOUT
[2023-12-18 16:06:02.890]: extractor Processed 10 entries (#10, +5, processing 6 and queued 0 entries)

home-gallery-api-server is the name of the api container. This container is available and I can ping it from inside the homegallery container just fine:

$ docker exec -it home-gallery /bin/sh
~ $ ping home-gallery-api-server
PING home-gallery-api-server (172.19.0.5): 56 data bytes
64 bytes from 172.19.0.5: seq=0 ttl=42 time=0.461 ms
64 bytes from 172.19.0.5: seq=1 ttl=42 time=0.342 ms
64 bytes from 172.19.0.5: seq=2 ttl=42 time=0.300 ms
64 bytes from 172.19.0.5: seq=3 ttl=42 time=0.315 ms
^C
--- home-gallery-api-server ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.300/0.354/0.461 ms

I did try with the original http://api:3000 before, with the same result.
Any Idea what causes this?

Johan

**Comment by xemle** [comment]
Hi @JohanE67

thank you for reporting your issue.

I tested the [docker compose](https://docs.home-gallery.org/install/index.html#docker-compose) installation instruction and was not able to reproduce your behavior. My setup worked out of the box.

What does `docker compose logs api` (replace api by your container setup) tells you? Can you post your docker-compose.yml as reference?

Which hardware and OS are you using?

**Comment by JohanE67** [comment]
Thanks for responding.
Here's the api container log (first lines):

home-gallery-api-server  | Loading tensorflow and models
home-gallery-api-server  | Load tensorflow width wasm backend in 406ms
home-gallery-api-server  | Loading model from /app/models/mobilenet-1-100/model.json
home-gallery-api-server  | Loaded mobilenet model in 2325ms
home-gallery-api-server  | Loaded faceapi model in 3292ms
home-gallery-api-server  | Loading model from /app/models/coco-ssd-mobilenet_v2/model.json
home-gallery-api-server  | Loaded coco ssd model in 6926ms
home-gallery-api-server  | Starting server
home-gallery-api-server  | Listen on port http://localhost:3000
home-gallery-api-server  | Setup api routes
home-gallery-api-server  | Server is up and running
home-gallery-api-server  | Read binary body with 76256 bytes
home-gallery-api-server  | ^[[0mPOST /faces ^[[32m200^[[0m 8190.299 ms - 148^[[0m
home-gallery-api-server  | Read binary body with 71199 bytes
home-gallery-api-server  | ^[[0mPOST /faces ^[[32m200^[[0m 8062.640 ms - 10514^[[0m
home-gallery-api-server  | Read binary body with 68219 bytes
home-gallery-api-server  | ^[[0mPOST /faces ^[[32m200^[[0m 5693.950 ms - 148^[[0m
home-gallery-api-server  | Read binary body with 85884 bytes
home-gallery-api-server  | ^[[0mPOST /faces ^[[32m200^[[0m 16388.810 ms - 104661^[[0m
home-gallery-api-server  | Read binary body with 50292 bytes
home-gallery-api-server  | ^[[0mPOST /faces ^[[32m200^[[0m 5546.344 ms - 148^[[0m
home-gallery-api-server  | Read binary body with 43491 bytes
home-gallery-api-server  | ^[[0mPOST /objects ^[[32m200^[[0m 3602.593 ms - 1204^[[0m
home-gallery-api-server  | Read binary body with 69313 bytes
home-gallery-api-server  | ^[[0mPOST /objects ^[[32m200^[[0m 3385.593 ms - 1330^[[0m
home-gallery-api-server  | Read binary body with 65406 bytes
home-gallery-api-server  | ^[[0mPOST /objects ^[[32m200^[[0m 3678.274 ms - 798^[[0m

And it goes on like this for 3839 lines up until now.

This is running on a [Rock64](https://www.pine64.org/devices/single-board-computers/rock64/), OS is [ArmBian](https://www.armbian.com/rock64/).

**Comment by JohanE67** [comment]
Docker-compose.yml:

version: "3.9"
services:
  api:
    # custom build via
    #build: packages/api-server
    image: xemle/home-gallery-api-server
    container_name: home-gallery-api-server
    environment:
      # TensorflowJS backends
      # - cpu: slowest and best support
      # - wasm: good perfromance for arm64 and amd64 platforms
      # - node: best performance on amd64 platform
      #- BACKEND=cpu
      - BACKEND=wasm
      #- BACKEND=node
    restart: unless-stopped
  gallery:
    # custom build via
    #build: .
    image: xemle/home-gallery
    container_name: home-gallery
    restart: unless-stopped
    environment:
      - GALLERY_API_SERVER=http://api:3000
      #- GALLERY_API_SERVER_CONCURRENT=1 # On low powered devices
      #- GALLERY_API_SERVER_TIMEOUT=60 # On low powered devices
      - GALLERY_OPEN_BROWSER=false
      # Use polling for safety of possible network mounts. Try 0 to use inotify via fs.watch
      - GALLERY_WATCH_POLL_INTERVAL=300
    volumes:
      - ./data:/data
      - /mnt/ssd/homegallery/storage:/data/storage
      # Mount your media directories below /data
      - /mnt/ssd/media/Photos:/data/Photos
        #- ${HOME}/Pictures:/data/Pictures
    ports:
      - "3030:3000"
    user: "${CURRENT_USER}"
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']
networks:
  default:
    name: rommenet
    external: true

**Comment by JohanE67** [comment]
Changes to gallery-config.yml:

sources:
  - dir: '/data/Photos'
    #index: '{configDir}/{configPrefix}{basename(dir)}.idx'
    # excludes are using gitignore patterns
    excludes:
      - '**/.filerun.thumbnails/*'
      #- .DS_Store
      #- ._*
      #- '*.tmp'
      - '*cache*'
    #excludeIfPresent: .galleryignore


  apiServer:
    url: http://home-gallery-api-server:3000
    timeout: 30
    concurrent: 5

**Comment by xemle** [comment]
> Here's the api container log (first lines):
> 
> ```
> home-gallery-api-server  | Loading tensorflow and models
> ...
> home-gallery-api-server  | Read binary body with 76256 bytes
> home-gallery-api-server  | ^[[0mPOST /faces ^[[32m200^[[0m 8190.299 ms - 148^[[0m
> ...
> ```
> 
> And it goes on like this for 3839 lines up until now.

So this looks good so far. So there are some requests to the internal docker api-server.

However it is a bit tricky to configure the gallery between docker environment and the configuration. The environment should overrule the configuration. So setup the api host in the `docker-compose.yml` would be a better place with

```
    environment:
      - GALLERY_API_SERVER=http://home-gallery-api-server:3000
      - GALLERY_API_SERVER_CONCURRENT=1 # On low powered devices
      - GALLERY_API_SERVER_TIMEOUT=60 # On low powered devices
```

than in the `gallery.config.yml`.

Apparently the configuration of `gallery.config.yml` is taken instead of the environment... Which is more a bug than a feature IMHO.

> This is running on a [Rock64](https://www.pine64.org/devices/single-board-computers/rock64/), OS is [ArmBian](https://www.armbian.com/rock64/).

Are there any `...-faces.json`, `...-objects.json` or `...-similarity-embeddings.json` files in the `data/storage` directory? I guess so. On low powered SoC systems like your congestion will appear. The extractor is pushing to fast new images to the api-server which needs time to process. So after some time the api-server slows down and the timeout on the extractor happens.

The log shows:

```
[2023-12-18 16:04:53.545]: cli.spawn Run cli with extract --index /data/config/Photos.idx --storage /data/storage --api-server http://home-gallery-api-server:3000/ --api-server-timeout 30 --api-server-concurrent 5 --journal 1218-gBOK
```

where `--api-server-concurrent 5` is set to a high value for an embedded CPU system. Please set it to 1. Also increase the timeout to 60 as the comments in the `docker-compose.yml` in the [docs](https://docs.home-gallery.org/install/index.html#docker-compose) suggests.

Please finalize all your imports and run `docker compose run gallery run import` at the end to fix all missing import steps and face detections. By default the import is executed by smaller chunks. If you run `docker compose run gallery run import` in between it will import all files in once which might be take time (e.g. for video previews) until you see any results. `run import` is a command to recheck that everything is in place.

**Comment by JohanE67** [comment]
Ok, thanks for the explanations. Maybe it would be a good idea to provide in the docs some more explanation on what a "low powered device" exactly means. Since the docs start with the software being built for Raspberry Pi type systems, I didn't consider mine (quad-core, 4GB mem) as particularly low-powered...

> Are there any ...-faces.json, ...-objects.json or ...-similarity-embeddings.json files in the data/storage directory? I guess so.
Yes there are! 

I will follow your suggestion, let the current import run to completion, then change the configurations and run a full import again. I will report results here. Thanks again for the help.

Johan

**Comment by xemle** [comment]
@JohanE67 I've updated the [docker-compose.yml](https://github.com/xemle/home-gallery/blob/master/docker-compose.yml#L21) to clarify the options. Also the compose env now overwrites the config (3da6389).

These fixes are released in v1.14.5

**Comment by JohanE67** [comment]
> @JohanE67 I've updated the [docker-compose.yml](https://github.com/xemle/home-gallery/blob/master/docker-compose.yml#L21) to clarify the options. Also the compose env now overwrites the config ([3da6389](https://github.com/xemle/home-gallery/commit/3da63890b280918a26cfd77794dca2ac3ece5232)).
> 
> These fixes are released in v1.14.5

Thanks for the updates. 
I guess I was confused by the statement "on _low-powered SoCs_". This led me to believe there would be a distinction between hi-powered (e.g. Pi 3b/4) and low-powered (e.g Pi1/2, Pi Zero) SoCs. I never took PCs/Servers into account here. So yes, I think this change in the [docker-compose.yml](https://github.com/xemle/home-gallery/blob/master/docker-compose.yml#L21) is an improvement. 

Meanwhile, the initial import had finished. I updated the config, pulled the new image and am now running a full import. Not seeing error messages, so it's looking good!

**Comment by JohanE67** [comment]
Meanwhile, the full import had completed successfully and everything appears to be in order now. I'm closing this issue. Thanks again for the help.

**Comment by xemle** [comment]
Awesome. Thank you for your feedback.
