### ISSUE TITLE
More Info on CameraSettings

### ISSUE THREAD

**Issue by cimba007** [xemle/home-gallery#113]
Hello,

it would be nice if the information would show a little bit more from the exif data.

As I don't know how to do a proper PullRequest but I still want to contribute .. here is my try:

https://github.com/xemle/home-gallery/blob/a220ec89802f13618ff0d5327c41ce71a81a3b46/packages/webapp/src/single/Details.tsx#L90

```
{title:"Camera Settings",value:`ISO ${e.iso}, Aperture ${e.aperture}, FocalLength ${e.focalLength}mm, ExposureTime ${e.exposureTime}`}
```

https://github.com/xemle/home-gallery/blob/a220ec89802f13618ff0d5327c41ce71a81a3b46/packages/database/src/media/exif.js#L78

```
...
whiteBalance: exif.WhiteBalance,
exposureTime: exif.ExposureTime
```

Other Data from Exif can be added the same way it seems. It might require a rebuild of the database to store this information.
If you want to make this change locally you just need to do the changes to.
- exif.js
- App.XXXX.js

**Comment by xemle** [comment]
Hi @cimba007

thank you for your input. you are on the right track. To create a proper PR you need to have a development setup with git and nodejs environment. I can recommend to use visual studio code as editor. Than you can check if your changes are working as desired. Some skeleton steps for the development setup is:

- install git, nodejs and visual studio code
- fork the project and checkout your home-gallery fork repository
- run `npm install`
- run `npm run build`
- create a branch `git checkout -b feature/webapp-add-camera-settings`
- add your changes in `packages/database` and `packages/webapp`
- run `npm run build`, rebuild your database via `./gallery.js run import`, restart the gallery to validate your changes. There are shortcuts for the webapp if the database is updated in `package/webapp` via `npm run dev`.
- commit your changes and push it to your fork
- create the PR on github

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
