### ISSUE TITLE
Issue with Windows Download Link

### ISSUE THREAD

**Issue by hirenshah** [xemle/home-gallery#117]
Read Me Link:
https://dl.home-gallery.org/dist/latest/home-gallery-latest-win-x64

Website Link:
https://dl.home-gallery.org/dist/latest/home-gallery-latest-win-x64.exe

Read Me one doesn't work :)

**Comment by xemle** [comment]
Hi @hirenshah 

Thank you very much for the hint. It is now fixed in the [master](https://github.com/xemle/home-gallery).
