### ISSUE TITLE
Cannot read property 'substr' of undefined while indexing

### ISSUE THREAD

**Issue by trashcoder** [xemle/home-gallery#12]
Hi, 
I downloaded the binary and the git repo. in both Versions i get this error message:

index.checksum Calculating ids for 56 entries with 117.7MB of total size 117.7MB (100.0%)
/root/home-gallery/packages/index/dist/checksum.js:92
      log.debug({duration: Date.now() - t0, bytes: entry.size}, `Calculated id ${sha1sum.substr(0, 7)}... for ${entry.filename} with ${humanize(entry.size)} (${bps(entry.size, t0)})`);
                                                                                         ^

TypeError: Cannot read property 'substr' of undefined
    at ReadStream.<anonymous> (/root/home-gallery/packages/index/dist/checksum.js:92:90)
    at ReadStream.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by trashcoder** [comment]
Found out, it'S a cifs error.

**Comment by xemle** [comment]
Thanks @trashcoder for trying HomeGallery and reporting this bug.

As you figure out it is a problem with the underlying filesystem. This error is correctly handled in [checksum.js](https://github.com/xemle/home-gallery/blob/master/packages/index/src/checksum.js#L85) - a return is missing in that case.

I will fix this bug and release a new release soon. Thank you again

---
For curiosity: How did you find this photo web gallery and what is your use case to solve?

**Comment by xemle** [comment]
Released bug fix v1.2.2 containing fix of your discovered bug. Awesome!

See [CHANGELOG.md](../blob/master/CHANGELOG.md#122---2021-08-18)

**Comment by trashcoder** [comment]
Thank you for this fast support. 

I found home gallery in the awesome selfhosted list on github.
