### ISSUE TITLE
Please add as an Unraid template

### ISSUE THREAD

**Issue by se4203** [xemle/home-gallery#121]
I'm running an Unraid home server and would love to install this app there.
Unfortunately I'm not comfortable enough with Docker to translate the Compose yaml into an Unraid docker template.
Can anyone here help?

**Comment by xemle** [comment]
Hi @se4203 

thank you very much for your request. Personal I do not know Unraid docker templates and can not help. If you find a solution feel free to publish this by a comment here.

Keep in mind that HomeGallery is a spare time project and depends on community feedback and contributions. So do not hesitate to provide helpful input for the next Unraid user here...

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
