### ISSUE TITLE
Dedicated mobile app?

### ISSUE THREAD

**Issue by CComparon** [xemle/home-gallery#125]
Home Gallery advertises itself as a "mobile friendly web gallery". I confirm that the UI looks pretty good on mobile (Chrome on Android), but am wondering if there are plans to offer a dedicated app for an even slicker exeperience?

Keep up the great work,
Cyril

**Comment by xemle** [comment]
Hi @CComparon thank you for your interest and your request.

The application can be installed as PWA on your mobile phone. Please try this first. On you mobile Chrome browser you can access the gallery and select "Install App" (or something similar) from the context menu.

A native mobile application for iOS and Android would need lots of effort and knowledge which I can not provide. An PR doing that would be great though.

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
