### ISSUE TITLE
Unable to download/access/pull Docker image

### ISSUE THREAD

**Issue by jessienab** [xemle/home-gallery#136]
https://hub.docker.com/r/xemle/home-gallery

Anytime I try to access this page for the docker image, I get an error message. When pulling with `docker pull`, the output html is a 404 error.

I tried multiple browsers and IPs (mobile data vs home network), and either this is an issue with the image, or something on Docker Hub's end; I'm just working backwards I guess starting at the least likely issue source, this repo.

Thank you!

EDIT: same error appears even logged into Docker Hub

**Comment by xemle** [comment]
Hi @jessienab 

According to the last docker build https://github.com/xemle/home-gallery/actions/runs/8794517392/job/24134082010 the image should have been updated.

I guess there is something with docker. I have re-triggered the last job. Let's see. In the meanwhile you can build the docker image locally by your own

**Comment by xemle** [comment]
Somehow the current Github action does not proceed. It requires further investigations. What a pity.

**Comment by xemle** [comment]
Up to know I had no luck to repair the docker image builds via github actions.

**Comment by xemle** [comment]
I disabled arm64 docker build via github action and docker images are build again.

Closing this issue.
