### ISSUE TITLE
Bulk removing tags feature

### ISSUE THREAD

**Issue by FullSoundBox** [xemle/home-gallery#137]
Hi, I've tried home-gallery project and so far it's working wonderfully. I feel I can learn a lot from this repo :)

As a suggestion, I've tried bulk editing tags, but it seems you can only add them to the selected images, but there is no removing option. For example, I mislabeled some photos and ended up mixed. I worked around this issue using another tag :grin: 

Also, I think it would be useful to reload the page automatically once you add new tags. I've tested this with my laptop and smartphone, and I have to reload the page to see the images again. I think this behavior is not happening only in my local build.

Again, this is a great project, and I found it really useful and fast :)

**Comment by FullSoundBox** [comment]
Thanks for the quick response!

Yes, I seem to have missed these steps. I think I should have investigated a little more inside the question mark of the menu :sweat_smile: I reproduced the steps you provided and I was able to remove the tag from the mislabeled pictures.

I'll try to read the documentation further the next time :stuck_out_tongue_closed_eyes:

**Comment by xemle** [comment]
No worries. Glad that your are able to remove the misspelled tags now. Enjoy.
