### ISSUE TITLE
throw new ERR_HTTP_HEADERS_SENT('set');

### ISSUE THREAD

**Issue by trashcoder** [xemle/home-gallery#14]
i get the following error message:

**Log**
server.api.database.read Read database file /root/home-gallery/.config/home-gallery/database.db with 518 entries 61ms
server.request 200 GET / 61ms
server.request 304 GET /app.css 2ms
server.request 304 GET /App.js 1ms
server.request 200 GET /api/database?offset=0&limit=5000 64ms
server.request 206 GET /fonts/fa-solid-900.woff2 145ms
server.api.events Events file /root/home-gallery/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
server.api.events Events file /root/home-gallery/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
node:_http_outgoing:573
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (/root/home-gallery/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/root/home-gallery/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/root/home-gallery/node_modules/express/lib/response.js:267:15)
    at /root/home-gallery/packages/server/dist/api/events/index.js:122:32
    at Interface.<anonymous> (/root/home-gallery/packages/events/dist/read-events.js:47:9)
    at Interface.emit (node:events:394:28)
    at ReadStream.onerror (node:readline:265:10)
    at ReadStream.emit (node:events:406:35) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Error: 1

**Steps are:**

1. run command ./gallery
2. select "Update and process source files"
3. select "Initial import (incremental processing)"
4. after import finish select "start server"
5. start browser and browse to home-gallery url
6. crash with log from above

**Comment by xemle** [comment]
I am supprised what kind of errors you discover. On side is it good to harden the software on the other side there are some test that should ensure good user experience at the start but:-/ I am sorry for that.

I will have a look at this one, too and appriciate your patience and your reporting.

**Comment by xemle** [comment]
Mm. I was not able to reproduce your bug. I have tried it on Linux/Debian from source (current master) and the latest binary (v1.2.2).

Could you give some hint of your system? Strange is that the log line `server.api.events Events file /root/...` appears twice.

Why are you running the gallery from root user? Are you using docker? If so, there are public docker images available on [docker hub](https://hub.docker.com/r/xemle/home-gallery).

**Comment by trashcoder** [comment]
Yes, i'm trying it as root and when i have enough experience with the installation and configuration i reinstall it in the linux container with a standard user.

**Comment by trashcoder** [comment]
My system is a proxmox linux container with ubuntu 2021.04 server, options nesting and cifs activated

**Comment by xemle** [comment]
Ah. You are running the gallery inside a proxmox container. No clue yet why you have this error. And I guess this error is still there and you can not start the server/see something in the browser, right?

Why not using the official HomeGallery image and mounting your cifs inside the container via volume?

**Comment by trashcoder** [comment]
ok, i'll try it today and give you a feedback.

**Comment by trashcoder** [comment]
Found a solution. The error appears only when the events.db is missing.
After creating one by command line

`touch events.db `

in the folder mentioned in the error message, the server doesn't crash anymore.

**Comment by xemle** [comment]
Thank you for your feedback and a solution.

According to the code the case of non existing event file should be covered. The error message "proves" it and I am still wondering why the log message appears twice.

Could you provide more details how to trigger this behavior? You are running the gallery in a proxmox container and it should be reproduceable in the container. So would it be possible to describe how you start and enter the container including your CPU arch and how you installing (and executing) the gallery?

**Comment by trashcoder** [comment]
i tried to make a list of commands i used to install home-gallery via promox ct, but i now have another problem while npm install, perhaps the tensorflow url leads to a 404.

**Comment by xemle** [comment]
tensorflow belongs to the `api-server` package which is not required for the gallery itself. Do you plan to use the `api-server` different than the official docker image or the public api.home-gallery.org service?

Which CPU arch do you have? For arm64 some 404 for tsjs-node are normal due missing arm64 support of precompiled libtensorflow.

Are you using the gallery from source? If so what it your use case instead of using docker or binary builds? Are you planning some modifications?

Through all your findings and efforts: Would it help to have a Q&A session via voice/video chat?

**Comment by trashcoder** [comment]
Yes, why not. But let me first check, if i can get the same state with a new linux container to make an instruction for reproducing the error.

**Comment by trashcoder** [comment]
Here we go:
 
- Create a CT with ubuntu 21.04 server as template (1GB Ram, 2 Cores and 16GB Bootdisk, options: privileged, nesting, cifs)
- in CLI: 
`apt update && apt upgrade -y`
`apt install git curl cifs-utils python build-essential -y`

- Get latest version of node
`curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -`
`apt install -y nodejs node-pre-gyp -y`

- get latest version of home-gallery
`git clone https://github.com/xemle/home-gallery.git`
`cd home-gallery`
`npm install`

- Then mounting the cifs drive
`mkdir ~/photo`
`mount -t cifs //192.168.0.xxx/photo ~/photo -o user=xxx,pass=xxx,rw,noserverino`
- configuring the gallery.config.yml
`cp gallery.config-example.yml gallery.config.yml`
and make some configuration.

- Building
`npm run build`

- run the server
`./gallery.js`

select "start-the-server"

Then i get this error message when i connect with my browser:
`server.api.events Events file /root/home-gallery/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
server.api.events Events file /root/home-gallery/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
node:_http_outgoing:573
    throw new ERR_HTTP_HEADERS_SENT('set');`

but after 
`touch ~/home-gallery/.config/home-gallery/events.db`

the server runs fine.

**Comment by xemle** [comment]
Oh. Cool. I do not know what CT is but with an official Ubuntu docker image I receive the same error.

```
docker run -ti --rm ubuntu
apt update && apt upgrade -y
apt install git curl cifs-utils python build-essential -y
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt install -y nodejs node-pre-gyp -y
git clone https://github.com/xemle/home-gallery.git
cd home-gallery
npm install
npm run build
cp gallery.config-example.yml gallery.config.yml
mkdir /root/Pictures
./gallery.js run server &
curl http://localhost:3000/api/events
```

Error message is

```
server.api.events Events file /root/.config/home-gallery/events.db does not exist yet. Create an event to
 initialize it                                                                                           
{"error":{"code":404,"message":"Events file does not exist yet. Create an event to initialize it"}}server
.api.events Events file /root/.config/home-gallery/events.db does not exist yet. Create an event to initi
alize it                                                                                                 
root@58286d9cb357:/home-gallery# node:_http_outgoing:573                                                 
    throw new ERR_HTTP_HEADERS_SENT('set');                                                             
    ^                                                                                                    
                                                                                                         
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client                      
    at new NodeError (node:internal/errors:371:5)                                                        
    at ServerResponse.setHeader (node:_http_outgoing:573:11)                                             
    at ServerResponse.header (/home-gallery/node_modules/express/lib/response.js:771:10)                 
    at ServerResponse.send (/home-gallery/node_modules/express/lib/response.js:170:12)                   
    at ServerResponse.json (/home-gallery/node_modules/express/lib/response.js:267:15)                   
    at /home-gallery/packages/server/dist/api/events/index.js:122:32                                     
    at Interface.<anonymous> (/home-gallery/packages/events/dist/read-events.js:47:9)                    
    at Interface.emit (node:events:394:28)                                                         
    at ReadStream.onerror (node:readline:265:10)                                                         
    at ReadStream.emit (node:events:406:35) {                                                            
  code: 'ERR_HTTP_HEADERS_SENT'                                                                          
}                                                                                                        
cli.run error Error: 1 452681:53:38
```

Now I can have a look at it.

**Comment by trashcoder** [comment]
A CT is a linux container within proxmox.

**Comment by xemle** [comment]
It seams to be a problem with node version 16. I get the error on node 16.7.0 but not on node v14.16.1. Strange.

If you like we can have a general chat at 21h Europe/Berlin time in https://gitter.im/home-gallery/community

**Comment by trashcoder** [comment]
Sorry, not today. But tomorrow i have time at 21h.

**Comment by xemle** [comment]
All right. Let's meet tomorrow. Awesome.

**Comment by xemle** [comment]
Regarding this ticket: Please use node 14 by now, since node 16 seems to make troubles. I will check this another time. So I will close ticket.

Further, I do recommend to use the binary in your CT unless you are planing to change the code.

Thank you very much for your valuable input and the chat. If there are any other findings, please do not hesitate to file an issue.

**Comment by timdonovanuk** [comment]
FYI `touch ~/home-gallery/.config/home-gallery/events.db` no longer seems to work as a workaround, as home-gallery never seems to init the db file, so when it tries to write an entry finds a 0 byte file.

**Comment by xemle** [comment]
Touching the event file `events.db` should only throw an error which is caused by the missing file marker. But that should not be an problem to run the server.

The problem with the node v16 should be fixed, too.

To understand your problem, could you describe command by command, how you init, start import the gallery?

**Comment by eksklawa** [comment]
HI, I experience the same error, I am new user of your application, today, I just followed quick-step process running these commands:

```curl -sL https://dl.home-gallery.org/dist/latest/home-gallery-latest-linux-x64 -o gallery
 chmod 755 gallery
 ./gallery run init --source /mnt/e/Photos2
 ./gallery run server &
 ./gallery run import --initial
```

The galleries are being processed but when I stop/start server I see the error:

```ja@dell:~$ ./gallery run server &
[1] 27823
ja@dell:~$ cli.run Starting server
cli.task.run Execute: /tmp/caxa/home-gallery/1.6.0/home-gallery/node/bin/node /tmp/caxa/home-gallery/1.6.0/home-gallery/gallery.js --log-level info --log-file /home/ja/.config/home-gallery/gallery.log --log-file-level debug server --storage /home/ja/.cache/home-gallery/storage --database /home/ja/.config/home-gallery/database.db --events /home/ja/.config/home-gallery/events.db
server Open Home Gallery on http://localhost:3000
cli.server Server started. Open it at http://localhost:3000
server.api.database.read Read database file /home/ja/.config/home-gallery/database.db with 892 entries 71ms
server.request 304 GET / 7ms
server.request 304 GET /app.ed18a1ab.css 2ms
server.request 304 GET /App.3ca70d38.js 1ms
server.request 304 GET /fonts/fa-solid-900.4dc05597.woff2 1ms
server.request 304 GET /api/database.json?offset=0&limit=5000 35ms
server.request 304 GET /manifest.webmanifest 3ms
server.api.events Events file /home/ja/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
server.request warn 404 GET /api/events.json 2ms
server.api.events Add new client 1659955520255
server.api.events Add new client 1659955543133
server.api.events Add new client 1659955543448
```

All commands are run as regular user, in his home folder,
Also, when I go to http://localhost:3000/ I see pictures but "Tags" are empty.
How to get all photos tags collected there, so I could search photos by geo-location?

The installation is run in WSL2 on Ubuntu 20.04:

```ja@dell:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
```

PS. The same error is also displayed everytime when I reload http://localhost:3000/

```server.api.events Events file /home/ja/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
server.request warn 404 GET /api/events.json 1ms
server.api.events Add new client 1659956115420
server.request 304 GET / 2ms
server.api.events Client connection closed. Remove client 1659956115420
server.request 304 GET /app.ed18a1ab.css 2ms
server.request 304 GET /App.3ca70d38.js 4ms
server.request 304 GET /favicon.ico 1ms
server.request 304 GET /manifest.webmanifest 1ms
server.request 304 GET /api/database.json?offset=0&limit=5000 8ms
server.api.events Events file /home/ja/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
server.request warn 404 GET /api/events.json 2ms
```

**Comment by xemle** [comment]
Hi @eksklawa 

> HI, I experience the same error, I am new user of your application, today, I just followed quick-step process running these commands:
> 
> ```
>  curl -sL https://dl.home-gallery.org/dist/latest/home-gallery-latest-linux-x64 -o gallery
>  chmod 755 gallery
>  ./gallery run init --source /mnt/e/Photos2
>  ./gallery run server &
>  ./gallery run import --initial
> ```
> 
> The galleries are being processed but when I stop/start server I see the error:
> 
> ```
> ja@dell:~$ ./gallery run server &
> [1] 27823
> ja@dell:~$ cli.run Starting server
> cli.task.run Execute: /tmp/caxa/home-gallery/1.6.0/home-gallery/node/bin/node /tmp/caxa/home-gallery/1.6.0/home-gallery/gallery.js --log-level info --log-file /home/ja/.config/home-gallery/gallery.log --log-file-level debug server --storage /home/ja/.cache/home-gallery/storage --database /home/ja/.config/home-gallery/database.db --events /home/ja/.config/home-gallery/events.db
> server Open Home Gallery on http://localhost:3000
> cli.server Server started. Open it at http://localhost:3000
> server.api.database.read Read database file /home/ja/.config/home-gallery/database.db with 892 entries 71ms
> server.request 304 GET / 7ms
> server.request 304 GET /app.ed18a1ab.css 2ms
> server.request 304 GET /App.3ca70d38.js 1ms
> server.request 304 GET /fonts/fa-solid-900.4dc05597.woff2 1ms
> server.request 304 GET /api/database.json?offset=0&limit=5000 35ms
> server.request 304 GET /manifest.webmanifest 3ms
> server.api.events Events file /home/ja/.config/home-gallery/events.db does not exist yet. Create an event to initialize it
> server.request warn 404 GET /api/events.json 2ms
> server.api.events Add new client 1659955520255
> server.api.events Add new client 1659955543133
> server.api.events Add new client 1659955543448
> ```
> 
> All commands are run as regular user, in his home folder,

For me all looks good so far. Your database has 892 entries, and the events are empty because you did not tag photos yet.

The `server.request 304` says only that this file is cached when you press reload. So every thing is fine.

> Also, when I go to http://localhost:3000/ I see pictures but "Tags" are empty. How to get all photos tags collected there, so I could search photos by geo-location?

On the Tags page you see embedded exif tags added via #11. Geo tags are not listed here. But you can type the address parts as search terms in the search bar.

So on the one hand I see "works as designed" on the other side I see that you expect something else. Could you describe what do you expect in the Tags page like at the [demo Tags page](https://demo.home-gallery.org/tags) or what you would like to do with the geo information?
