### ISSUE TITLE
Github Security Lab Security Report

### ISSUE THREAD

**Issue by Kwstubbs** [xemle/home-gallery#140]
Hi maintainers, 

Github Security Lab has found some potential vulnerabilities in home-gallery. Can you please open [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) or give us an email contact so that we can privately disclose these vulnerabilities?  

Thank you,
Kevin

**Comment by xemle** [comment]
Thank you @Kwstubbs for poking me for the security report. I have enable it and close this issue.

Please reopen the issue for further input.
