### ISSUE TITLE
Not handling multiple subject tags

### ISSUE THREAD

**Issue by fire-eggs** [xemle/home-gallery#149]
Trying out the pre-packaged Linux exe. I have some images where I've established multiple Exif.Subject tags. Home-gallery successfully imports those tags, but as a single tag instead of the expected multiple tags.

E.g. if I've used ExifTool to add multiple Subject tags to an image:
```
exiftool -Subject=castle -Subject=knight knight.jpg
```
the resulting Exif.Subject string is `castle, knight`. When imported into home-gallery, those should be two distinct tags.

**Comment by xemle** [comment]
Hi @fire-eggs 

Thank you for reporting the issue. The gallery works as intended. Each subject is treated as single distinct tag `castle` and `knight`.

Do I understand you correctly: Your expectation is that multiple subject tags should be imported only as one tag into the gallery joined by a comma `, ` and the resulting tag should be `castle, knight`?

Can you describe your usecase or current workflow of joined tags? What problem do you like to solve?

Are you aware that you can query single tags by the [query language](https://docs.home-gallery.org/search/index.html) like `tag:castle or tag:knight` or `tag:castle and tag:knight`?

**Comment by fire-eggs** [comment]
Thank you for the quick response! Sorry for being imprecise.

When importing exif subject tags, the currently available Linux exe version of home-gallery does not treat each subject as a distinct tag. The tags are imported as `castle, knight`. The desired behavior is to import as distinct tags `castle` and `knight`.

Here is a screen cap showing the current behavior:
![image](https://github.com/user-attachments/assets/809708eb-189f-4f9e-a120-dc9a317a1138)

For the sample image, the three intended-to-be-distinct tags `illustration`, `castle` and `ex libris` have been imported as one combined tag.

I entered the issue because in this code:
```
const addUniqValues = (result, values) => toArray(values).forEach(value => {
  if (!result.includes(value)) {
    result.push(value)
  }
})
```
from `packages/database/src/media/tags.js` I don't see any handling of comma-separated-values, which the original exif tags are stored as. My understanding of javascript is limited so I may have misunderstood.

**Comment by xemle** [comment]
Hi @fire-eggs 

That is strange that the subjects are joined as one single tag.

Would you mind to send the example image with the subjects so I can better check and reproduce it?

Could it be that the image contains the compound subject already? Have you checked it via `exiftool -json -Subject knight.jpg | jq .` and are the subjects an array as in my example picture?

```
[
  {
    "SourceFile": "knight.jpg",
    "Subject": [
      "castle",
      "knight"
    ]
  }
]
```
![knight](https://github.com/user-attachments/assets/a751ef14-aa1d-449c-87d4-2af8b156ce41)

**Comment by fire-eggs** [comment]
Sure thing. knight.jpg attached. Here is the output from exiftool:
```
kevin@BRIX2:~/dpix/000to-sort4$ exiftool -json -Subject knight.jpg | jq
[
  {
    "SourceFile": "knight.jpg",
    "Subject": [
      "castle",
      "finis",
      "knight",
      "illustration"
    ]
  }
]
kevin@BRIX2:~/dpix/000to-sort4$ exiftool -Subject knight.jpg
Subject                         : castle, finis, knight, illustration
```
![knight](https://github.com/user-attachments/assets/91e44d62-d20a-495b-94ac-78fdd643debf)

Kevin

**Comment by xemle** [comment]
Thank you for your image. The compound tag `castle, finis, knight, illustration` comes from the `HierarchicalSubject`:

```
exiftool -json knight.jpg | jq . | grep -C2 castle
    "Format": "image/jpeg",
    "Subject": [
      "castle",
      "finis",
      "knight",
      "illustration"
    ],
    "HierarchicalSubject": "castle, finis, knight, illustration",
    "ColorMode": "RGB",
    "ICCProfileName": "",
```

So while the tag extraction of `Subject` works as expected, you HierarchicalSubject value is not split. A quick internet search seems that it is not documented, how to split a HierarchicalSubject. A [forum entry of exiftool](https://exiftool.org/forum/index.php?topic=9208.0) about HierarchicalSubject split the values by the pipe char `|`. So I am not sure what is the correct way for the algorithm of HomeGallery...

Do you have a suggestion?

**Comment by fire-eggs** [comment]
I just figured it out myself. Nice catch! 

Digging a little bit, it seems the HierarchicalSubject tag is specific to Adobe Lightroom (from [here](https://exiftool.org/TagNames/XMP.html), search for "lightroom").

This [forum discussion](https://photo.stackexchange.com/questions/47209/is-there-a-well-known-way-to-store-a-taxonomy-hierarchy-in-xmp-iptc-or-exif) shows there could be multiple tag hierarchies. On consideration, I think the current behavior of home-gallery is "correct". To use the example from that forum, if I establish a tag hierarchy of `Army|vehicle|Fennek`, that is a single "tag" for home-gallery. If I search for `Fennek` that should match in that "tag".

I believe this is a tagging error on my part: I should not be duplicating the Subject tags into the HierarchicalSubject field. I don't use Adobe Lightroom, and can no longer remember my reasoning behind the duplication. I'll be fixing my images.

**Comment by xemle** [comment]
Awesome. Happy that we found a solution.

Are there any open issues regarding your HierarchicalSubject or can we close this issue?

**Comment by fire-eggs** [comment]
Nothing further from me. Thank you for the conversation and thank you for the project!
