### ISSUE TITLE
basePath configuration broken

### ISSUE THREAD

**Issue by MarioSob** [xemle/home-gallery#151]
Recently I upgraded gallery from version I installed around April 2024 to newest one. I use docker compose to launch it on Linux x86 64bit. Unfortunately I discovered that support for configuration entry basePath is broken in newest version. Configuration of:
`  basePath: '/hg/mario/'`
worked perfectly before but now it causes frontend to try to fetch resources from for example:
`https://domain/hg/mario/hgmario/App.2aa10ed6.css`
This makes page unable to render at all.

**Comment by xemle** [comment]
Hi @MarioSob Thank you for your issue and highlighting the problem well.

I've fixed it in the newest master 14c0f73 and the base path of `/hg/mario/` should working again.

Can you confirm it?

**Comment by xemle** [comment]
@MarioSob Please see discussions on [gitter](https://gitter.im/home-gallery/community) regarding the basePath. A new server option `prefix` was introduced.

**Comment by MarioSob** [comment]
I confirm it works now. Thank you for fixing this. I only have "basePath" configured in configuration file and it seems to be sufficient.
