### ISSUE TITLE
Logger spams with access logs

### ISSUE THREAD

**Issue by MarioSob** [xemle/home-gallery#153]
When gallery (running in docker compose) is configured with console logger like the following:
```
logger:
  - type: console
    level: info
```
it spams logs with entries about every request, like the following:
`[2024-09-14 15:55:48.433]: server.request 200 GET /api/database/tree/204e338cab03b849e47106e5c1bc3a4ceb7d9d2f.json 9ms`
even though logging level is set to INFO, not debug or trace.

**Comment by xemle** [comment]
Hi,

currently each request is logged. The function `customLogLevel` decides which log level to use per request. The default log level is `info`. See [server/src/logger-middleware.js](https://github.com/xemle/home-gallery/blob/master/packages/server/src/logger-middleware.js#L16).

For `/files` request path the log level is `debug`. Do you think `/api` request path should be also at log level `debug`?

**Comment by MarioSob** [comment]
Yes, I think that would be consistent.

**Comment by xemle** [comment]
Hi @MarioSob I've downgraded log levels in 0f47ac6. Please try it and check if this change is sufficient for you

**Comment by MarioSob** [comment]
I confirm it works as I would desire now. Thank you.

**Comment by MarioSob** [comment]
I confirm it works as I would desire now. Thank you.
