### ISSUE TITLE
Feature Request: option to directly serve images

### ISSUE THREAD

**Issue by tereteru** [xemle/home-gallery#19]
With large libraries (mine has about 1.5 million files) the compressed pictures take a huge amount of disk space. I thought using a dedicated disk would be a good idea, so I hooked up a 500GB disk to my server... But it was completely filled up after scanning ~500'000 images!
Knowing that my collection is 1.2TB big, the compressed pics would probably take up more space than the originals after a full scan...

It would be awesome if home-gallery could serve the original images themselves and not a compressed copy, or to compress them on the fly as they're requested, then delete them after a while.

**Comment by xemle** [comment]
> Basically, I'm downloading content from artists I like (from many sources, Twitter, Instagram, etc...), which is why I have that many images, and why most of them aren't very "high quality". Many of them have a "720p-tier" resolution. To browse them, I wanted a webapp that didn't have a lot of features (all I really need is to sort them either by date or folder, + a global view of all pictures),

OK. Got it and I do understand your settings.

Currently there is no check if the input is smaller than the requested preview size. This could be fixed.

Further for your usecase it would be helpful to have an option that the smaller original images are symlinked to the storage as largest preview. You would than save some bytes. Further it would have the drawback that the original files needs to be present so the gallery can serve these images. What do you think?

> and Home Gallery was the only one that fit my needs pretty much perfectly. It's not too dumb (as opposed to many static gallery generators, which also need to completely reindex all pictures every time), but also not bloated (it doesn't try to be a full fledged cloud service like most). And on top of that, it's very fast, and handles tons of pictures with no issue.

Thank you. Glad that you are enjoying the gallery.

> I also have a secondary instance with family pictures, but at only ~15'000 images, I've yet to encounter an issue with that one :)

Please file a issue there, too if you have problems for your family pictures.

**Comment by tereteru** [comment]
> OK. Got it and I do understand your settings.
> 
> Currently there is no check if the input is smaller than the requested preview size. This could be fixed.
> 
> Further for your usecase it would be helpful to have an option that the smaller original images are symlinked to the storage as largest preview. You would than save some bytes. Further it would have the drawback that the original files needs to be present so the gallery can serve these images. What do you think?

Yes, having the option to symlink either smaller pictures (or all of them) would solve my problem!
Needing the original file at all times isn't really an issue for me. My pictures are all stored locally on the NAS I'm running home-gallery from, and if I delete some, then I want them gone from the gallery as well.

**Comment by xemle** [comment]
> Yes, having the option to symlink either smaller pictures (or all of them) would solve my problem! Needing the original file at all times isn't really an issue for me.

Yes. While it is not required in your case, the option to symlink the original and symlink larger previews to smaller images will cover a broader audience. For some people it might be nice to serve originals as well. And this would be a nice feature for me to support. 

So with the option "symlink originals" you allow the gallery to serve images from your source directory. With the preview size check that only smaller previews are calculated you cover your case: All your downloaded images stay at your source directory and only smaller previews are generated.

If you turn off "symlink originals" only smaller previews will show up. (Internally the gallery uses a predefined preview size list, see [extractor index.js](https://github.com/xemle/home-gallery/blob/master/packages/extractor/src/index.js#L32) and this list is traversed in the web app)

I keep your request in my mind. Currently the life is very busy and can not implement this. If you offer a PR I am happy to support you.

> My pictures are all stored locally on the NAS I'm running home-gallery from, and if I delete some, then I want them gone from the gallery as well.

That will be ensured. The gallery creates a file index. If a file deletion is detected it will be removed from the database.

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
