### ISSUE TITLE
The scanner does not follow symlinks

### ISSUE THREAD

**Issue by tereteru** [xemle/home-gallery#20]
home-gallery does not seem to detect symlinked pictures. When using a directory full of them, the scan ends almost instantly, and nothing is added to the gallery.

**Comment by xemle** [comment]
I could not reproduce your issue with following test

* Create a source dir with symlinks of a file and a dir and a file outside of the source root
```
dira/filea.png
dirb -> dira
fileb.png
filec.png -> fileb.png
filed.png -> ../filed.png
```
* Bootstrap the gallery with current master: Only 2 files `dira/filea.png` and `fileb.png` are shown
* Changed the `fs.lstat` to `fs.stat` and build the source again
* Update the gallery: 3 files are shown including `filed.png`

Could you describe what you did differently?

**Comment by tereteru** [comment]
Hi! Sorry for the late reply. I didn't delete the database at first, but after doing so, it works fine. Thanks a lot!

**Comment by xemle** [comment]
Symbolic links are now followed by #107 (> v1.14.4)
