### ISSUE TITLE
How can i make autodetect and reindex new file?

### ISSUE THREAD

**Issue by Bartixxx32** [xemle/home-gallery#21]
Hello, i use the home-gallery in docker compose, and my question is.

Is it possible to auto detect changes in media directory? like i upload image, and after some time it gonna show on the gallery.

Thanks :)

**Comment by xemle** [comment]
Thank you very much for using HomeGallery.

You need to run the import command `docker-compose exec gallery /app/gallery.js run import --update` after uploading images which will detect media changes and imports new files. A running server will reload the database and the browser will show new media. See [docer-compose](https://docs.home-gallery.org/install/index.html#docker-compose) and [import](https://docs.home-gallery.org/cli/index.html#run-import-command) documentation section.

If you like to do it automatically you need to setup a cron task to run this step periodically. I would advice to run it every day.

**Comment by Bartixxx32** [comment]
oh, okay thats makes sense i tought same about cron, but i hoped i only need tweak config or so, but if there is no buildin feature gonna use cron. Thanks :)

**Comment by xemle** [comment]
Did cron work for you? Did it solve your problem?

**Comment by Bartixxx32** [comment]
Yes, thanks for help it can be closed now :)
