### ISSUE TITLE
Face recognition

### ISSUE THREAD

**Issue by mirozv** [xemle/home-gallery#22]
Hi !
What about implement face recognition ? ;)
I tried this project ( https://docs.deepstack.cc/face-recognition/index.html ) and it looks really good. It can be run in a docker and its implementation is not complicated.

**Comment by xemle** [comment]
Face recognition is already implemented via [FaceAPI](https://github.com/vladmandic/face-api).

You need to press the (i) icon on the bottom on image view to see media details. The red face boxes are clickable and you will see similar faces in the photo stream. You can check it via images with faces like [example 1](https://demo.home-gallery.org/view/1870cf3d386fd19dbcdfb369e72fdd5d86ddaab5) or [example 2](https://demo.home-gallery.org/view/75cbb6c18b834469f77f527ff96c1ea39fedc07a).

![image](https://user-images.githubusercontent.com/261850/147062013-7056899a-45fe-480c-b910-0b39b12fce55.png)

I do not demo many face image due privacy concerns. So I recommend to try the gallery and check if its face recognition fits your needs.

**Comment by mirozv** [comment]
Great, thx ;)

**Comment by Todd1561** [comment]
Is there a way to name faces and then search on those names?

**Comment by xemle** [comment]
Hi @Todd1561 

Naming of faces it not implemented yet. PRs are welcome.

[#6](https://github.com/xemle/home-gallery/issues/6#issuecomment-853908211) has also some discussions about face tagging. Would you mind to describe your usecase for the faces in detail?

**Comment by Todd1561** [comment]
I'm basically trying to replace Google Photos with a self-hosted solution, which I think you'll find is what most of your potential users are trying to do as Google clamps down on what the free version of Photos can do.  The google Photos system can detect faces and group the same person together, you can then name that person.  This is extremely powerful as I can just do a search on "Henry" and get all the pictures of Henry in my library.

**Comment by xemle** [comment]
Thank you for your insights. I could imagine that face tagging feature is powerful.

With HomeGallery you can tap on an face an see similar faces. So you need a seed image and tag it with "Henry" to find other images like "Henry".

Maybe you try HomeGallery with a small set of photos to check if it fits your needs. Than you can also validate if the accuracy of face detection is sufficient with this web gallery by finding enough good matches. I am curious how well or bad the face detection is compared Google.

Of cause I am happy if you stay but an other web gallery alternative is [PhotoPrism](https://photoprism.app) or have a look at https://github.com/awesome-selfhosted/awesome-selfhosted#photo-and-video-galleries for other solutions.

**Comment by Todd1561** [comment]
Yep I've set it up and placed a few dozen images in my test system.  It seems to do a decent job at detecting faces, but recognizing (the process of knowing that 2 faces are the same) seems to be hit or miss - it pulls up a lot of unrelated images.  Even Google will have this issue, to a lesser extent, but gives you the opportunity to fix errors to train the model.  Unfortunately, I don't think this is a problem easily solved.  Platforms like Google, AWS, Microsoft, Apple have access to billions of images and millions of users that are training their system each day.  I just don't think it's possible for an open source AI system to complete on that level.  Maybe one day.

I have looked at PhotoPrism and actually spent several days getting it set up and trained.  It worked OK, but definitely a far cry from Google Photos.  Eventually the Docker container broke for some reason and I put the project aside.  Your 2nd link is actually how I came across your app.  

Anyway, you're doing great things here, I think HomeGallery has a lot of potential and I like what you've done with it so far, I'll stay tuned to see what comes next!  The fact that it runs natively on Windows, doesn't require Docker, can play nicely with my existing media file structure. has seamless continuous scrolling and a slick UI are all great things.  IMO the only things it's missing is a true timeline scroll (again, like Google), the ability to multi-select and batch export original image files, and better AI/ML (face recognition and object detection).

**Comment by xemle** [comment]
Thank you for your reply, your time and the flowers.

One more questions: You are the 2nd person who request the time scroll and emphasis how important it is (which is a lot for the low traffic of issues here ;-) ). I could not imagine that it that important. Would you mind to describe why this feature is so delighting and helpful? This would help me maybe to understand its importance.

**Comment by Todd1561** [comment]
Sure, for me (and I imagine most people) the reason they use a system like yours or Google Photos is to help them find pictures.  I can often remember a rough time estimate of when something took place and then I can scroll to that month in Google Photos and typically within a few seconds I've found what I need.  Most other systems allow for searching based on date ranges or maybe the ability to drill into a specific year, but what Google (and Microsoft Photos works the same) has done is really powerful.

**Comment by xemle** [comment]
Thank you @Todd1561 for the quick reply. So it is basically often used navigation tool through the archive - maybe also the main tool to browse through the archive...

If so it makes absolutely sense to have it ;-)

**Comment by Todd1561** [comment]
Yep, I don't think I've ever been in Google Photos and not used it to navigate around.

**Comment by xemle** [comment]
Thank you @atlas-shrugged08 for your poke regarding face tagging. I will put it on my list but sadly some other topics have more priority.

Since I do not have a clear view how to implement the UI of the face tagging any screenshots or scribbles can help here. And finally PRs are also welcome.
