### ISSUE TITLE
No items in gallery, after importing

### ISSUE THREAD

**Issue by jtagcat** [xemle/home-gallery#23]
I ran:
```
/app/gallery.js run init --source /data/Pictures
/app/gallery.js run import --update
```

and yet, still, the pages are all blank:
![image](https://user-images.githubusercontent.com/38327267/148485556-17f6d5b7-dd2c-4bb1-b1ed-80197b6bc938.png)

How can I help?

**Comment by xemle** [comment]
Thank you for using HomeGallery

Could you provide some more context details to support you proper?

I looks like you are using the gallery via docker. Did you check that `/data/Pictures` is proper mounted and has some files which are readable? Did you check the log file for any errors?

**Comment by jtagcat** [comment]
> Did you check that /data/Pictures is proper mounted
It is.

> Did you check the log file for any errors?
no

**Comment by jtagcat** [comment]
I ran it again on a smaller folder / a subset of directories. `ESOCKETTIMEDOUT`. Though, now it shows images fine, dunno.
