### ISSUE TITLE
Option to download the original file

### ISSUE THREAD

**Issue by asmaps** [xemle/home-gallery#25]
How complicated would it be to implement a function to download the original image? If you can give me a quickstart and point me to a good entrypoint file I could also try implementing it as a PR.

PS: Thanks for this awesome project, by far the best image gallery I found (and I tried them all)

**Comment by xemle** [comment]
> How complicated would it be to implement a function to download the original image? If you can give me a quickstart and point me to a good entrypoint file I could also try implementing it as a PR.

There is a similar feature requrest in #19. The idea is to implement an option to symlink or copy original files to the storage directory. This will be done in the extractor.

PRs are welcome. Some implementation hints are:

- Add an option to the CLI package for the extractor
- Implement an pipeline task in the extractor which consumes this option. See [vibrant.js](https://github.com/xemle/home-gallery/blob/master/packages/extractor/src/vibrant.js) as example
- I recommend to have a dedicated storage suffix `original` with original file extension
- Adapt the database to add the original file to the database
- Implement a download link in the webapp in the details view, if the original file is available. This file will have cryptic filename on static servers
- Optional implement a middleware in the server to overwrite the original filename for the cryptic filename

You can also PM me for details

> PS: Thanks for this awesome project, by far the best image gallery I found (and I tried them all)

Thank you very much for your flowers.

For curiosity: What usecase/problem do you solve with HomeGallery?

**Comment by asmaps** [comment]
> > How complicated would it be to implement a function to download the original image? If you can give me a quickstart and point me to a good entrypoint file I could also try implementing it as a PR.
> 
> There is a similar feature requrest in #19. The idea is to implement an option to symlink or copy original files to the storage directory. This will be done in the extractor.
> 
> PRs are welcome. Some implementation hints are:
> 
> * Add an option to the CLI package for the extractor
> * Implement an pipeline task in the extractor which consumes this option. See [vibrant.js](https://github.com/xemle/home-gallery/blob/master/packages/extractor/src/vibrant.js) as example
> * I recommend to have a dedicated storage suffix `original` with original file extension
> * Adapt the database to add the original file to the database
> * Implement a download link in the webapp in the details view, if the original file is available. This file will have cryptic filename on static servers
> * Optional implement a middleware in the server to overwrite the original filename for the cryptic filename
> 
> You can also PM me for details

I will look into it as soon as I have time. Will let you know.

> 
> > PS: Thanks for this awesome project, by far the best image gallery I found (and I tried them all)
> 
> Thank you very much for your flowers.
> 
> For curiosity: What usecase/problem do you solve with HomeGallery?

Hosting the private photo/video collection of 2 people. The phones sync their images to nextcloud, rclone pulls them on the local disk and homegallery then displays them nicely. The 2 collections are separated in 2 directories/homegallery instances/domains.
I wanted to migrate away from Google Photos to something selfhosted for a while, but all galleries had major drawbacks. E.g:

* slow (nextcloud integrated gallery)
* wrong usecase intention (e.g. main use to build an online gallery for your website)
* bad/no search or filtering
* no possibility to quickly get a photo from a point in time (usecase: you look for something and know roughly when you took the picture)

**Comment by xemle** [comment]
> > For curiosity: What usecase/problem do you solve with HomeGallery?
> 
> Hosting the private photo/video collection of 2 people. The phones sync their images to nextcloud, rclone pulls them on the local disk and homegallery then displays them nicely. The 2 collections are separated in 2 directories/homegallery instances/domains. I wanted to migrate away from Google Photos to something selfhosted for a while, but all galleries had major drawbacks. E.g:
> 
> * slow (nextcloud integrated gallery)
> * wrong usecase intention (e.g. main use to build an online gallery for your website)
> * bad/no search or filtering
> * no possibility to quickly get a photo from a point in time (usecase: you look for something and know roughly when you took the picture)

Thank you for your insights.

Hope you are happy with HomeGallery ;-)

**Comment by darrepac** [comment]
Sounds to me a must to , after viewing a preview version, be able to get the full resolution image.
1st to see it better by getting the full resolution
2nd to be able to share it to someone...

I look for a photo, found it, look at it with some friends... "Send it to me"...I can't currently, or just the HD version.

**Comment by xemle** [comment]
> not being to obtain original file seems like showstopper to me.

Thank you @EsEnZeT for your honest feedback. I can not tell when this feature will come. Please subscribe to this project to receive any updates on this.

Further do not hesitate to try other OSS like [photoprism](https://photoprism.app/), [photoview](https://photoview.github.io/), [photostructure](https://photostructure.com/) (no OSS) or any other Google Photos alternative from [selfhosted photo and video galleries](https://github.com/awesome-selfhosted/awesome-selfhosted#photo-and-video-galleries) and enjoy your memories

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
