### ISSUE TITLE
Timeline / Filter by month

### ISSUE THREAD

**Issue by asmaps** [xemle/home-gallery#26]
Any thoughts on implementing the possibility to filter not only by year, but also by month?
Also it would be awesome to have a "timeline scrollbar" like the one in Google Photos (but honestly not really an idea how to do that efficiently)

**Comment by xemle** [comment]
> Any thoughts on implementing the possibility to filter not only by year, but also by month?

Currently I am working on extending the search capabilities also by month, day (of month), height, image ratio, explicit tag and others including comparison like `month > 6 and tag = vacation`

I plan to release this feature in the next two weeks.

> Also it would be awesome to have a "timeline scrollbar" like the one in Google Photos (but honestly not really an idea how to do that efficiently)

That is an nice but also an expensive feature. I keep that in my mind. PR are welcome.

My thoughts about an implementation would be to: The height of each row and the total height of the photo stream is known. So it should be possible to implement an mapping to the timeline scaled down to the view height which will be rendered in a special component. This component becomes visible on scrolling.

**Comment by xemle** [comment]
@asmaps Just want to drop a note of the new 1.4.1 release including an advance search. See [Search Docs](https://docs.home-gallery.org/webapp/index.html#search) for details.

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
