### ISSUE TITLE
Missing preview results in bad quality pics

### ISSUE THREAD

**Issue by gyorgyistvan** [xemle/home-gallery#27]
I uploaded a pic that is 1328x747.
In the webapp, it's very blurry.

It's blurry because it displays the 320 preview on my fullhd monitor.
The large image is missing from the HTML and also as a preview file.

I'm not sure, but I think this is the reason:

In case of images with a width between 1280 and 1920, the web app looks for a 1920px wide preview, but this preview is not generated, because the original pic is smaller than that.

I checked the code, maybe these places cause the problem:

1. In this file, largeSize is set to 1920:
File: `/packages/webapp/src/single/MediaViewImage.tsx`
Line: 16 -> `const largeSize = width <= 1280 ? 1280 : 1920;`

2. In this file, 1920 is filtered from the preview sizes, that file is not even generated:
File: `/packages/extractor/src/image-preview.js`
Line: 66 -> `const previewSizes = imagePreviewSizes.filter(s => s <= size)`

If I resize my browser to 1279px, and refresh, it works well, cause then it shows the preview that is 1280px wide.

**Comment by xemle** [comment]
> I uploaded a pic that is 1328x747. In the webapp, it's very blurry.
> 
> It's blurry because it displays the 320 preview on my fullhd monitor. The large image is missing from the HTML and also as a preview file.

You found a bug. Congratulations and thank you so much for reporting it.

> I'm not sure, but I think this is the reason:
> 
> In case of images with a width between 1280 and 1920, the web app looks for a 1920px wide preview, but this preview is not generated, because the original pic is smaller than that.
> 
> I checked the code, maybe these places cause the problem:
> 
>     1. In this file, largeSize is set to 1920:
>        File: `/packages/webapp/src/single/MediaViewImage.tsx`
>        Line: 16 -> `const largeSize = width <= 1280 ? 1280 : 1920;`

That is the correct area to fix it. Good catch!

>     2. In this file, 1920 is filtered from the preview sizes, that file is not even generated:
>        File: `/packages/extractor/src/image-preview.js`
>        Line: 66 -> `const previewSizes = imagePreviewSizes.filter(s => s <= size)`

2. was introduced in the last release by ec489d4 to reduce preview disk space for smaller images as reported in #19. Since I usually have larger images than FullHD I did not discovered this issue.

> If I resize my browser to 1279px, and refresh, it works well, cause then it shows the preview that is 1280px wide.

Thank you very much for this bug report. A PR is welcome to fix it. Otherwise I will do it after my current vacation in two weeks.

**Comment by xemle** [comment]
All right, I'll do it

Thanks again for reporting this issue

**Comment by gyorgyistvan** [comment]
Sure thing.
Thanks for home-gallery! It's awesome!

**Comment by xemle** [comment]
Fixed in 8f05b09

Thank you for the report.
