### ISSUE TITLE
Docker Compose Issue

### ISSUE THREAD

**Issue by kebanks** [xemle/home-gallery#30]
When I run the Compose provided, I get the following error

services.gallery.expose is invalid: should be of the format 'PORT[/PROTOCOL]' : exit status 1

**Comment by xemle** [comment]
Hi @kebanks 

Thanks for this hint and reporting this issue. I guess 'expose' should be 'port'. But I will check that in detail after my vacation.

**Comment by caustee** [comment]
I had the same problem and it got fixed after I changed expose to ports.

**Comment by xemle** [comment]
Thanks again for the report. I've fixed it in 9512e5c
