### ISSUE TITLE
Address management

### ISSUE THREAD

**Issue by asitemade4u** [xemle/home-gallery#36]
The way geolocations are managed in HG is very intuitive but does not fit all use cases, far from it (I am thinking of Japan, besides my own town).
I live in NYC and my photos are both geolocated in Manhattan and Brooklyn.
Unfortunately, street names are the same in both boroughs, as they were united late in the 19th c.

So, when HG writes, for example:

![image](https://user-images.githubusercontent.com/11460106/169313609-c0f49529-66dd-4597-8e3a-c8a25881ca43.png)

it is not very clear wether the photo is located in Brooklyn or Manhattan as there are _major_ streets bearing that name in both boroughs.
Unfortunately, there is no way to get that information from the reverse geocoding tool you're using.
But there is a real need for improvement there.
S.

**Comment by xemle** [comment]
Thank you very much for this input. Its very enlightening to receive further cases which should/could be covered.

For the geo reverse lookup openstreetmap (precisely [nominatim](https://nominatim.org) service) is used in the extractor step. In the storage directory there are *-geo-reverse.json files which contains the nominatim results which will be used in the database builder step to produce the address. See [map-media.js](https://github.com/xemle/home-gallery/blob/master/packages/database/src/map-media.js#L307) in the database package. Than in the view the database information is stringifyed.

Would you mind to check your *-geo-reverse.json files and if your usecase can be mapped? Please suggest your mapping improvement if possible.

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
