### ISSUE TITLE
Support for simple keyboard shortcuts for navigating in MediaView?

### ISSUE THREAD

**Issue by theaerotoad** [xemle/home-gallery#4]
First off, this is a _really_ interesting interactive gallery application.  Thanks for sharing it with the world.  The browsing and exploring functionality on mobile devices (chrome and firefox on Android) is snappy and optimized for touch devices.  For a library of about 40,000 items, the loading and searching speed is impressive.

When using on desktop, though, I frequently find myself getting lost when trying to return to the main listing (/) by searching for the small white fa-th grid icon or the chevrons on the left and right.  Left and right swipes are fine on a mobile device, as is "back" to return to the gallery.  I think the "fast" equivalent on non-mobile interfaces is single-key shortcuts.  What do you think about including some simple keyboard navigation options in that view?

I've not hacked much within react, though some searching shows there may be keyboard shortcuts possible.  Other javascript gallery applications I've tried lately use arrow for left and right in views, and escape to return to the index back.  So maybe something like:

* Left, Right: Navigate to previous or next
* Escape: Return to main view grid
* i: toggle details
* t or z: for timeline

What do you think?

**Comment by xemle** [comment]
Hi @theaerotoad

thank you for trying the gallery and your positiv feedback.

Currently I am using mostly the mobile version. So the desktop shortcuts are a great idea.

Due my time constraints the shortcut feature is a question on prioritization. On my current list is to tune the initial experiance where the initial import is done iterative (or bulk steps) and file logging..

How can we support each other? Could you sell your needs a bit more? Are you experimenting or using the gallery? What is your use case to solve with the gallery?

I could need some public advertisements like tweets, blogs or something similar ;-)

**Comment by theaerotoad** [comment]
Thanks for the response, @xemle.

**I'll give adding keyboard shortcuts a try, and (assuming I can get it to work) I'll make it available if you want to incorporate it.**  I've tinkered with [mousetrap](https://craig.is/killing/mice) in a personal python+flask+sqlite+javascript note-taking application I wrote, and it worked well there.

I agree with the priority on tuning the initial experience--the iterative approach would mean new users could start exploring right away.  It took a full week to get all my images converted and tagged in home-gallery.

My own use case is likely to stay in the "self-hosted" category, with use by myself and family on the same network.  Like many of us, I've got a 20+ year odd photo archive.  In the last month, I've deployed and tinkered with several other self-hosted gallery options (lychee, photoprism, photoview, etc.).  None of these seem to scale as well as home-gallery, so I've opted to pick it up, and make some tweaks along the way.

I'm running it on a Raspberry pi 4 with a separate x86 machine running the api server in docker.  I've made a few minor changes (reverse geo address lookups in English, which looks like you recently added as well), date formatting changes (year-month-date preference), and trying to have tags / directories in the detailed view as links to search, as another way to explore.  My javascript is exceedingly rough.

As for public advertisements, I'm not much of a social media personality.  I'll happily point others I know in this direction, but my audience is pretty small.  That said--I expect there's a group of folks (like me) that may transitioning from reliance on [cloud-based photo services](https://blog.google/products/photos/storage-changes/) soon.  The common way of migrating out of Google Photos exports images and `json` files with some extra metadata, like faces and comments.  It might be interesting to pull that data in read-only (either into /storage or into embeddings or exif data) if/when the importer finds it.  Listing home-gallery is a fast, self-hosted option to cruise Google Photos exports may get some additional users this way...

**Comment by xemle** [comment]
Thank ypu for your reply and details.

Regarding shortcuts, you could give a try to [react-hotkeys-hook](https://github.com/JohannesKlauss/react-hotkeys-hook) within the single media view component.

Regarding non issue related topics I will response in [gitter chat](https://gitter.im/home-gallery/community)

**Comment by xemle** [comment]
Shortcuts are now available since 1.2.0, see commit 55d1870
