### ISSUE TITLE
Help for some debug

### ISSUE THREAD

**Issue by darrepac** [xemle/home-gallery#40]
Hi

I came back to Home Gallery to see the progress made.
I updated the docker image and remove all previous database. I did an import --update but I lost the terminal connection during the process after few hours.
So I did import --update again and here is the output:
```
$ docker-compose exec gallery /app/gallery.js run import --update
cli.run Import online sources from: /data/Pictures
cli.task.run Execute: /usr/local/bin/node /app/gallery.js --log-level info --log-file /data/config/gallery.log --log-file-level debug index --directory /data/Pictures --index /data/config/Pictures.idx --exclude-if-present .galleryignore --journal 0626-iKTZ
index Updating file index for directory /data/Pictures
index.create Read 40445 files in /data/Pictures 15:59
index.merge Merged 40445 entries 20s
index.update No changes found 03:38
index.journal Journal /data/config/Pictures.idx.0626-iKTZ.journal created
index Updated file index for directory /data/Pictures 21:23
cli.task.run Execute: /usr/local/bin/node /app/gallery.js --log-level info --log-file /data/config/gallery.log --log-file-level debug extract --index /data/config/Pictures.idx --storage /data/storage --journal 0626-iKTZ
extractor.image.resize Use sharp to resize images
index.readStream Reading file index journal /data/config/Pictures.idx.0626-iKTZ.journal
cli.extract Extract all meta data and calculated all preview files from 0 entries 53s
cli.task.run Execute: /usr/local/bin/node --max-old-space-size=2048 /app/gallery.js --log-level info --log-file /data/config/gallery.log --log-file-level debug database --index /data/config/Pictures.idx --journal 0626-iKTZ --storage /data/storage --database /data/config/database.db
index.readStream Reading file index journal /data/config/Pictures.idx.0626-iKTZ.journal
database.build Created 0 database entries 6.2s
database.mergeJournal Read file index journal /data/config/Pictures.idx.0626-iKTZ.journal
cli.database Database unchanged: Error: Journals contain no changes
cli.task.run Execute: /usr/local/bin/node /app/gallery.js --log-level info --log-file /data/config/gallery.log --log-file-level debug index journal --index /data/config/Pictures.idx --journal 0626-iKTZ -r
index.journal Remove journal 0626-iKTZ from file index /data/config/Pictures.idx
cli.run Have a good day...
```

On website side, I have no photos at all:
![image](https://user-images.githubusercontent.com/7128994/175829556-54cb00e9-2a24-4d7e-b538-ad19ad08bce6.png)

Any hints?
Thanks

**Comment by xemle** [comment]
> I came back to Home Gallery to see the progress made.

Awesome. Welcome back.

> I updated the docker image and remove all previous database. I did an import --update but I lost the terminal connection 
during the process after few hours. So I did import --update again

`--update` looks for new files to process - which is basically process only the diff of the file index.

> index.update No changes found 03:38

If an import process failed before it might have all files in the index but not in the database - it is most probably the case here

> cli.extract Extract all meta data and calculated all preview files from 0 entries 53s

Since the file index has no updates no files were processed by the extractor.

> database.build Created 0 database entries 6.2s
> database.mergeJournal Read file index journal /data/config/Pictures.idx.0626-iKTZ.journal
> cli.database Database unchanged: Error: Journals contain no changes

The database wont be changed if there are no files updates. If the database creation might failed before so that the database does not exists or has no entries.

> On website side, I have no photos at all:

Unfortunately in your case that looks fine for the `--update` option.

To solve your problem: run the `import` without further option of `--update` or `--initial` as stated in the [docs](https://docs.home-gallery.org/cli/index.html#run-import-command):


>Note
>If the import command is aborted (eg. by the user), you should run a full import to ensure that all meta data and all previews are available.

If this does not help or you have further questions, please do not hesitate to report them.

**Comment by darrepac** [comment]
Thanks! to be honest, I did not find what was the "--" option for the full import...in fact it is import without any "--" option! 
Will run it and see

**Comment by darrepac** [comment]
So I run `docker-compose exec gallery /app/gallery.js run import`
So as I read, it can take days to do the first import (I have 40k photos). I guess I can detach the process with the `-d` flag but then I have no more log output of the process going... Neither in the container log. How I can check where the process is, etc (and it is not stopped)

**Comment by darrepac** [comment]
Ok I stop my previous run and did it again with `--initial` option. I can follow with the logs.
After a while, because my understandings is that some photos would be viewable quickly, I go to the web part and try to see something: nothing appear.
In the log, I particularly see:
`{"level":30,"time":1656348151919,"pid":17,"hostname":"6546a3b0278e","module":"server.api.database","msg":"Database file is not loaded yet."}`
...
`{"level":30,"time":1656348152053,"pid":17,"hostname":"6546a3b0278e","module":"server.api.events","msg":"Events file /data/config/events.db does not exist yet. Create an event to initialize it"}`

Everything normal?

**Comment by xemle** [comment]
If the server is started and no database exists, that message is expected.

The theory of initial index would be, that the first 200 files are processed, than 500, than a bit more. If you only process images, it should go quick eg. a few minutes. I assume about 5 sec per image that would bee 1000 sec (~ 15 min) for the first batch.

Have you deleted the `*.idx` files before? Does the browser shows some pics?

**Comment by darrepac** [comment]
It is running since more than 1 hour and the web is displaying nothing.
`Have you deleted the *.idx files before?
`
No did nothing. Thought the `--initial flag` was enough.

`Does the browser shows some pics?`
No

**Comment by xemle** [comment]
>>> If you want to start allover I recommend to remove the index files and start the import with the `--initial` option.

>>Have you deleted the `*.idx` files before?

>No did nothing. Thought the --initial flag was enough.

Mm. You need to delete them first. Otherwise the given files are known to the gallery and you have to wait...

The import step consists of following steps: 1) create/update file index, 2) extract preview and meta data based on the file index 3) create/update the database (see [workflow docs](https://docs.home-gallery.org/internals/index.html#workflow)). The `--initial` option creates a file index and aborts after some amount of new files, continues to step 2) and 3) and repeats with 1) for new files until all files are updated.

I am sorry for this misunderstanding.

**Comment by xemle** [comment]
> Seems to work much better! thanks!

Awesome.

... and after you imported all your images you can import and convert the videos ;-)

**Comment by timdonovanuk** [comment]
I'm also running into `server.api.events Events file /opt/home-gallery/.config/home-gallery/events.db does not exist yet. Create an event to initialize it`

Which means tagging does not work for me. I've run all the commands as shown in the quickstart guide. Not sure what I'm supposed to do to generate events.db if the 1) gallery init script doesn't create it 2) running the server doesn't create it 3) the gallery import init (?) script doesn't create it. I am also completely confused by the various cmd line options available.

Any help appreciated! Thanks.

**Comment by timdonovanuk** [comment]
Seems I am having the same issue as here: https://github.com/xemle/home-gallery/issues/14

Also running in a Proxmox LCX (but that shouldn't really matter for something like creating or checking if a file exists!)

**Comment by xemle** [comment]
> I'm also running into `server.api.events Events file /opt/home-gallery/.config/home-gallery/events.db does not exist yet. Create an event to initialize it`

OK. Maybe the log message could be improved to `Events file /opt/home-gallery/.config/home-gallery/events.db does not exist yet. It will be created on the first tag`

> Which means tagging does not work for me. I've run all the commands as shown in the quickstart guide. Not sure what I'm supposed to do to generate events.db if the 1) gallery init script doesn't create it 2) running the server doesn't create it 3) the gallery import init (?) script doesn't create it.

So tagging should work - when the init, import and starting of the gallery is successfull

> I am also completely confused by the various cmd line options available.

The cmd line options should be valuable if you like to dig deeper to the possibilities of HomeGallery. For the normal usage the `./gallery run ...` commands should be sufficient to init, start, import and update your media gallery. See [docs here](https://docs.home-gallery.org/cli/index.html#run-command).

> Any help appreciated! Thanks.

If questions are still open, please rise further questions.
