### ISSUE TITLE
Parallelizing imports

### ISSUE THREAD

**Issue by bridadan** [xemle/home-gallery#44]
I've really enjoyed using your project, thanks for sharing it! Definitely the most responsive photo gallery I've used so far 🙂 

I noticed that the import process is currently single threaded. Is there any reason why it couldn't be parallelized across multiple threads? There's a `worker_threads` API that looks interesting, I haven't used it before: https://nodejs.org/docs/latest-v14.x/api/worker_threads.html

**Comment by xemle** [comment]
Thank you for your positive feedback. Glad that you like the responsiveness, too.

Could you describe in detail where you experience slow processing and what is your expectation? What exactly would you propose to parallelize?

**Comment by bridadan** [comment]
I'm using the Docker Compose setup on my server, so to import more pictures I run:

```
docker compose run gallery run import --update
```

I'm currently at the stage where I'm adding hundreds of pictures and videos from various backups, so the import takes several hours. I forgot to take logs so I don't have an exact time, sorry about that :sweat_smile:. I ran `top` during the import and I noticed that only one of my CPU cores were being used. I'm assuming the import process is limited by the speed of your CPU, so I was wondering if we could process multiple pictures at once using multiple CPU cores. I know that node.js is single threaded, however it looks like the `worker_threads` offers a way to create multiple threads so you can make use of more CPU cores.

Is there anything in the import process that relies on the images being processed in a specific order? Or could it be parallelized across multiple CPU cores?

**Comment by xemle** [comment]
You are using the import with arg `--update` which is not recommended to use at the beginning. So I am asking myself: do you want to optimize/fasten the import and UX process or do you want to optimize the CPU usage? The first should be fixable with the `--initial` arg. If you have question on that, please let me know.

Further I assume that the focus is to view the personal media archive. The process to import it is a required step but can consume time - or in other words: My assumption is that the import is not time critical.

IMHO the most time consuming tasks are video transcoding and object/face/similarity detection which should be already parallelized. I can not remember but I assume that the video trancoding with ffmpeg will consume more than one thread. Further the object/face/similarity detection depends on your setting. This could be parallelized if required by spawning and proxy multiple API nodes, true. Eg. via nginx.

For me, using `worker_thread` optimizes the gallery on some corners where it is not so important at the end. If you host your photos at home you are most probably willing to accept a waiting time if the result - browsing the gallery itself - is fine. You can afford to wait until the last image is resized and the last video is tanscoded and imported.

Of cause you might have a different opinion and PRs are welcome to fix your needs.

I hope is not to destructive or demotivating. Please continue the discussion if you like. And I am happy for further inputs. Thank you for reaching out and for using the web gallery.

**Comment by bridadan** [comment]
Hi @xemle, sorry for not being clear before. I've already run the `import --initial` command for my initial import. Since that's done, I'm running `import --update` for each new batch of photos. On my last run of `import --update` I noticed only a CPU core was in use. I provide 4 to the VM I run the gallery in, so I was thinking it may be possible to speed up the import process.

You're definitely right, time is not critical and I _am_ willing to wait for the processing to finish. But, I'm also always interested in how the system works and if there's any opportunity for (hopefully) small changes that improve performance.

I did not check CPU usage when the videos were being imported but I'm willing to bet you're right that ffmpeg parallelizes video transcoding by default. I believe I checked when the import process was importing images. So yeah, not asking you to change anything, more just wondering about the internals of the import process. On my next import I'll try to take better notes, maybe I'll be able to make the modifications myself :smile:

**Comment by xemle** [comment]
Thank you very much for the further details. I am happy that you are used `--initial` before and we share the basic expectations and interests.

Also the image resizing should be using multiple CPU cores using sharp package (see its [fast notes](https://sharp.pixelplumbing.com/#fast)). But to be honest I never checked how to speedup the import process in detail.

If you are interested in optimizing the import we could do also a 1:1 session talking about the internals and share ideas.

**Comment by bridadan** [comment]
I appreciate the offer! I'll let you know if I think that's necessary after I've poked around more.
