### ISSUE TITLE
feature request: delete picture from database

### ISSUE THREAD

**Issue by ElFishi** [xemle/home-gallery#47]
Sometimes pictures get uploaded to the drive that are not worth publishing when viewed on the big screen. 
Would be nice to have the option on the web interface to delete pictures from the database.

**Comment by xemle** [comment]
Thank you for your input and your issue. I could also use that function because other family members do not sort the pictures as I do and so we have a lots of series of the same scene...

I would recommend to support a trash action. So images are marked to be trashed and are not shown by default. The trashed images could be shown separately. These trash commands could be stored as additional user event like the tag events in the events database.

IMHO the gallery should not perform any file deletion by default and the filesystem should be the master.

There could be a export command to perform the deletion on the filesystem if desired and should be used with care.

Any comments?

**Comment by ElFishi** [comment]
I am not familiar with the db-model, but functionally I would want hg (1) to not use/show pictures I tag as deleted. If it can also (2) delete those pictures from the file system, but that would be an extra step. 
My FR is mostly about (1). 
(2) is nice but would have lower priority for me.

**Comment by xemle** [comment]
Thank you for the clarification.

Other question: My use-case of "deleting images" are often picture series which are not cleared before syncing to the gallery - I have a lot of them. My idea was to support an auto grouping of sequences of similar images and showing only one image. Would that help you, too? What functionality would you prefer or use? The manual trash feature or auto grouping of sequences?

**Comment by ElFishi** [comment]
My use case are shots that turn out to be not so cool when inspected more closely or two shots of the same subject where I only want to present the better one. Those are rather single instances and not sequences. If whole sequences would need to go, I imagine they'd be chronological. In any case I wouldn't trust an algorithm that only shows 1 representative picture and kills swathes of pictures.

**Comment by Milkysunshine** [comment]
I also would love this feature. 

The way it is now, I would have to delete everything, remove the unwanted photos, and re-scan over 33,000 files which takes about a day.

I am surprised --update doesn't handle removed files. 

I definitely love the project, and I am looking forward to future improvements.

**Comment by xemle** [comment]
> I also would love this feature.

Thank you for your request

> The way it is now, I would have to delete everything, remove the unwanted photos, and re-scan over 33,000 files which takes about a day.

Mm. Re-scan takes more than a day? I am suprised. It should be handled within minutes. Some seconds to identify the deleted images and a few minutes to build the database.

So the question is in which environment you are running the gallery and which command you are using. Would you mind to provide some details to identify a bug, a configuration issue or a human mistake?

> I definitely love the project, and I am looking forward to future improvements.

Thank you very much. On my pipe there is finalizing the map feature and than we will see.

**Comment by Milkysunshine** [comment]
> > 
> 
> Mm. Re-scan takes more than a day? I am suprised. It should be handled within minutes. Some seconds to identify the deleted images and a few minutes to build the database.
> 

I have my data directory mounted from a share on a busy server. Because everything has to go over the network, my setup is inherently slower than most

**Comment by xemle** [comment]
> I have my data directory mounted from a share on a busy server. Because everything has to go over the network, my setup is inherently slower than most

Mm. Maybe two features might help you to solve network bottlenecks

- If it is possible, run the gallery on the remote server and fetch only the gallery data to your machine via `fetch` command. So the heavy file lifting is executed on the file server while the gallery runs on you local server
- If that is not working, you might have stable directories where you do not change files like delete photos. So you can split this directories in different sources/file indices and select only these directories for update where you are working actively via the interactive shell command
  - You can also mark the stable directories as offline, so normal import command should work, too

**Comment by Milkysunshine** [comment]
>     * If it is possible, run the gallery on the remote server and fetch only the gallery data to your machine via `fetch` command. So the heavy file lifting is executed on the file server while the gallery runs on you local server

This could possibly work, but I don't think truenas scale allows things to be sideloaded. Scale is pretty locked down. I'd have to look into options for that setup

**Comment by xemle** [comment]
@xemle The [fetch command](https://docs.home-gallery.org/cli/index.html#export-command) has now an `--delete` option, where deleted files from a remote are removed on the local gallery.

It is not deleting as requested but it goes in that direction.

**Comment by SimonPae** [comment]
What happens to those images deleted in the source folder?
Am I correct with the assumptions that:
- the images get deleted from the database which results in the fact that they are not shown in the gallery anymore
- the generated preview images still exist and do not get deleted

Any chance to get the filepaths of those preview images?
Speaking of if members of the gallery do not filter out bad images prior adding them to the gallery, how can we delete them? If we can get a list of filepaths to the source and preview images of the ones taged with "DELETE" or something we can use other tools (cli) to get rid of them. Not a nice an integrated logic but at least a good working workaround I would say. What do you think?

**Comment by xemle** [comment]
> What happens to those images deleted in the source folder? Am I correct with the assumptions that:
> 
>     * the images get deleted from the database which results in the fact that they are not shown in the gallery anymore
> 
>     * the generated preview images still exist and do not get deleted

Correct.

The CLI has a [storage purge](https://docs.home-gallery.org/cli/index.html#storage-command) command to cleanup orphan files in the storage. This is the usecase the file is deleted on the filesystem by someone/something else.

> Any chance to get the filepaths of those preview images? Speaking of if members of the gallery do not filter out bad images prior adding them to the gallery, how can we delete them? If we can get a list of filepaths to the source and preview images of the ones taged with "DELETE" or something we can use other tools (cli) to get rid of them. Not a nice an integrated logic but at least a good working workaround I would say. What do you think?

This is the case you want to delete a file via HomeGallery: The API of the gallery server can be queried with the search term. eg

curl 'http://localhost:3000/api/database.json?q=tag:DELETE' | jq .data[].files[0]

will give you all media tagged with ˋDELETEˋ and the first (and largest) file struct of each. The filenames are relative to the source directory and the source directory is not given for "security" reasons.

Maybe this helps and you can build your CLI.

Since the gallery is "just" a view layer on top of media directories and these media are crucial, I prefer to leave the deletion of files to some other software.

Further I would like to export given tags to standard xmp sidecar files. (Creating and updating sidecar files are acceptable on source directories for me. While deleting files not - at least not yet.) The deletion could be marked as a xmp rate property with 0 as value. HomeGallery could than ignore these media with ratings of 0 on database creation.

What is your workflow/usecase to have the deletion feature?

**Comment by SimonPae** [comment]
@xemle Nice. 
> What is your workflow/usecase to have the deletion feature?

I was just worried to feed lots of images without the possibility to "get rid of them". With a DELETE Tag and your api endpoint I can get the original filename as well as the preview filenames. Deleting them on the disk should be no hard task (gonna write a bash script or sth.).

> Since the gallery is "just" a view layer on top of media directories and these media are crucial, I prefer to leave the deletion of files to some other software.

I totally support it.
Are there any other endpoints to the gallery?
I could not find any in the documentation.

**Comment by xemle** [comment]
> > What is your workflow/usecase to have the deletion feature?
> 
> I was just worried to feed lots of images without the possibility to "get rid of them". With a DELETE Tag and your api endpoint I can get the original filename as well as the preview filenames. Deleting them on the disk should be no hard task (gonna write a bash script or sth.).

I am happy that you can deal with this solution.

> > Since the gallery is "just" a view layer on top of media directories and these media are crucial, I prefer to leave the deletion of files to some other software.
> 
> I totally support it. Are there any other endpoints to the gallery? I could not find any in the documentation.

Currently there are:

* `GET /api/database.json` with `q`, `limit`, `offset` query parameter to read the database. The `q` parameter excepts same search queries like in the web app [search input](https://docs.home-gallery.org/webapp/index.html#search)
* `GET /api/events.json` to get all events
* `POST /api/events` to create a new user event. Currently only create/delete tags
* `GET /api/events/stream` as SSE (server send events) to subscribe to events. It broadcasts new user events or if the database file was changed on disk

The webapp loads the database and subscribes to the event stream. It updates the internal database state in the browser by applying the user events.

The `GET /api/database.json` returns always the updated entries with applied user events - except the static export version of cause.

What API you are looking for? Anything in mind?

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
