### ISSUE TITLE
Feature Request: Remove Tag from Image

### ISSUE THREAD

**Issue by Gulluth** [xemle/home-gallery#48]
I deployed home-gallery yesterday, and I am enjoying it so far. While testing, I applied some arbitrary tags to some files, and have noticed that there is no way in the UI that I can find to remove a tag once it has been applied. I haven't investigated removing tags from the console yet.

Having looked through the other bugs reported here, I see you have asked for use-cases so here is one that is possibly unique.

My use case is to have a progressive webapp to load a gallery of images to share with my discord community. These images are inspirational posts created by myself and other community members to support a table-top role playing game the discord server is focused on. These images are largely generated by Midjourney AI, but may also include artist images from various locations on the internet. There are very few images taken from a digital camera.

I did see in another bug report that you recommend changing the API URL to disable the machine learning, and I think this is something I will definitely do. The images in the gallery are largely abstract and science-fantasy, and I do not want automatic organization or face recognition, and instead want to rely 100% on our community to correctly tag these images.

**Comment by xemle** [comment]
Hi @Gulluth 

thank you very much for using HomeGallery and opening your troubles here

> I deployed home-gallery yesterday, and I am enjoying it so far. While testing, I applied some arbitrary tags to some files, and have noticed that there is no way in the UI that I can find to remove a tag once it has been applied. I haven't investigated removing tags from the console yet.

From the [edit mode docs](https://docs.home-gallery.org/webapp/index.html#edit-mode):

> In the edit dialog you can add comma separated tags to the selected images. A minus prefix removes a tag.
>
> The input "vacation, rome, -city" adds the tag "vacation" and the tag "rome" but removes the tag "city".

Currently the removal of tags is only supported in the web app. An CLI action to delete tags or export of tags to XMP sidecar files are NIY. Do you think it would help to support a CLI action to delete tags?

> I did see in another bug report that you recommend changing the API URL to disable the machine learning, and I think this is something I will definitely do. The images in the gallery are largely abstract and science-fantasy, and I do not want automatic organization or face recognition, and instead want to rely 100% on our community to correctly tag these images.

Thank you for giving some insights for your use-case which helps me more to understand the different needs and requirements.

**Comment by Gulluth** [comment]
@xemle thanks for pointing out that the ability to remove tags from the UI does exist, but is not obvious. I can think of two ways to improve upon this. 

1. Include the instructions and example in the modal window that pops up when tagging.
2. Use a UI element to display the tag, and include an ![image](https://user-images.githubusercontent.com/1114761/184995680-229fd237-153e-4197-a246-9767781bd0f3.png) to allow it to be removed.

I don't think I would personally use the CLI to manage tags. Once an app is running, I rarely want to ssh to my docker server to perform a task the UI should support.

**Comment by xemle** [comment]
@Gulluth  thank you for your input

I will take it into account when the tag input field gets into the (implementation) focus.

HomeGallery uses its own CSS (for fun). So there is no given component to integrate from a major CSS framework. Further these frameworks do not support every required feature yet. A nice tagging input is supported from time to time but I am looking for an option where tags can be marked as deleted and a (x) icon removes this tag from the input list. It is tricky.

PRs are also welcome :-)

**Comment by xemle** [comment]
@Gulluth I am currently working on this feature and it will be released soon.

Inspired by @tokenwizard I will also implement the tag edit for single media

**Comment by Gulluth** [comment]
Looking forward to testing this out, thank you @xemle

**Comment by xemle** [comment]
1.9.0 is released with the new tag input dialog

- edit tags for media selection via edit mode and single media through detail view
- show single tags as own ui component
- remove single tag component
- toggle single tag between add and remove action
- autocomplete from exisiting tags
- autocomplete matches parts of tags: e.g. needle is 'fr' finds 'francisco', 'fire' or 'alfred'
- recent tag pollish

You can check the new feature on the [demo web gallery](https://demo.home-gallery.org).

**Comment by Gulluth** [comment]
Better late than never, I finally tested out the updated tagging feature and it is great. Thank you @xemle

**Comment by xemle** [comment]
@Gulluth Thank you for your response and testing!
