### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by darrepac** [xemle/home-gallery#5]
Hi

As stated in an other issue, I started with docker without much success and I moved to linux binary to test the home-gallery solution.
But when I try to start the server, it exists:
`pascal@NewNas:~/Home-Gallery$ ./home-gallery-latest-linux-x64
Loaded gallery configuration from gallery.config.yml
✔ Gallery main menu · server
Execute: DEBUG=server* /tmp/caxa/home-gallery/1.0.1/home-gallery/node/bin/node /tmp/caxa/home-gallery/1.0.1/home-gallery/cli.js server --storage /home/pascal/.cache/home-gallery/storage --database /home/pascal/.config/home-gallery/database.db --events /home/pascal/.config/home-gallery/events.db --port 1000
Have a good day...
`
Any hint?
Do I have to intsall any dependencies?

thanks

**Comment by darrepac** [comment]
Seems it doesn't like 1000 as port, with 8080, it works better.

**Comment by xemle** [comment]
Port 1000 might not worked due the privilaged port (1-1024).

If you playing with docker, you can leave the port 3000 in the container and map the host port with `-p` parameter like `-p 8080:3000`.
