### ISSUE TITLE
import -i crashed 

### ISSUE THREAD

**Issue by Tint0ri** [xemle/home-gallery#51]
after days import with -i flag. process stopped by this error message:

TypeError: Cannot read property 'toFixed' of undefined
    at FfmpegCommand.<anonymous> (/app/packages/extractor/dist/video.js:55:94)
    at FfmpegCommand.emit (events.js:400:28)
    at Object.extractProgress (/app/node_modules/fluent-ffmpeg/lib/utils.js:345:15)
at /app/node_modules/fluent-ffmpeg/lib/processor.js:529:23
at /app/node_modules/fluent-ffmpeg/lib/utils.js:387:34
at Array.forEach (<anonymous>)
at emit (/app/node_modules/fluent-ffmpeg/lib/utils.js:387:11)
at /app/node_modules/fluent-ffmpeg/lib/utils.js:419:13
at Array.forEach (<anonymous>)
at Object.append (/app/node_modules/fluent-ffmpeg/lib/utils.js:418:20)
cli.run error Error: 7 462505:22:23

**Comment by Tint0ri** [comment]
I'm running HG docker on a **low powered NAS device with ARM cpu**. HG works great when I side loaded the API server docker on my PC. I really wish HG can finish the init job and put all my 140K+ photos and videos online. Cause other photo galleries are too heavy to consume all resources when index the photos and videos for the first time, make the NAS device was not accessable. But  with HG, it still be usable.
Thanks for your great work.

**Comment by xemle** [comment]
> after days import with -i flag. process stopped by this error message:
> 
> TypeError: Cannot read property 'toFixed' of undefined
> at FfmpegCommand. (/app/packages/extractor/dist/video.js:55:94)

Mm. OK. The error occurs in the [video extrator](https://github.com/xemle/home-gallery/blob/master/packages/extractor/src/video.js#L54) at the logging

```
      if (now > last + intervalMs) {
        log.info(`Video conversion of ${entry} at ${progress.timemark} is ${progress.percent.toFixed()}% done`);
        last = now;
      }
```

and `percent` should be set by the npm module [fluent-ffmpeg](https://www.npmjs.com/package/fluent-ffmpeg). There is also an [old issue #550](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/550) and a more recent [stackoverflow post](https://stackoverflow.com/questions/65457944/fluent-ffmpeg-progress-percent-return-undefined) on that. Maybe it is different on ARM with native binary which you are using...

I have to check the video conversion on docker with ARM CPU which you are using. This will take some time.

What exact docker image you are using?

If possible you can hot fix it by changing the logging line in `/app/packages/extractor/dist/video.js` to

```
log.info(`Video conversion of ${entry} at ${progress.timemark} is ${progress.percent?.toFixed()}% done`);
```

Note the question mark at `percent?`.

> I'm running HG docker on a low powered NAS device with ARM cpu. [...] Cause other photo galleries are too heavy to consume all resources when index the photos and videos for the first time, make the NAS device was not accessable. But with HG, it still be usable.
> Thanks for your great work.

Thank you for the flowers

**Comment by xemle** [comment]
Hi @Tint0ri 

I've published a new docker image with the fixed percentage at 94b9512. Please retest and report if this issue is solved

**Comment by Tint0ri** [comment]
Thx. Pull the new image and test again.

**Comment by xemle** [comment]
@Tint0ri do you have any updates on this issue?

**Comment by Tint0ri** [comment]
HG is still doing the import job for the first time. About 30% in progress (40K+).  There are two issues for now"
1. like https://github.com/xemle/home-gallery/issues/49, Some photos are not show in gallery. I will try to fix it by import again without flag when initial  import process finised. 
2. According to heavy load to process video convert, some process (sucha as face detection, geo revserse lookup, ...) may not successfule for some photos. I wonder is there any way to retry  those process for uncomplished photos.
Thanks.

**Comment by xemle** [comment]
> HG is still doing the import job for the first time. About 30% in progress (40K+). The toFixed issue was gone.

Good to hear

> There are two issues for now"
>
> - Same as https://github.com/xemle/home-gallery/issues/49, some photos are not show in gallery. I will try to fix it by import again without flag when initial import process finised.
> - According to heavy load for video convert, some processes (sucha as face detection, geo reverse lookup, ...) may not successful return for some photos. I wonder is there any way to retry those processes for uncomplished photos.

Yes sure. Run the full import step afterwards, than (missing) files should be (re)created and the media database will be build again. No problem.

You said that you are running the gallery on an ARM NAS device which is most probably not that performant - especially for videos. Have you the possibility to run/build the gallery on another machine and than move/clone the gallery to the NAS to save some time? Or exclude the videos first, enjoy all the images and than let the videos render in parallel? If you need help, please let me know.

FYI My 62h video material took about 1 month to complete on a mini ATX with Intel Celeron J3xxx something. So some patience is required.

**Comment by Tint0ri** [comment]
Great. 👏 🌷 

Looking forward to testing the geo photo map feature in the next release.

**Comment by xemle** [comment]
Thank you @Tint0ri for closing this issue. Happy, that the original issue was solved.

Regarding to you issue with low powered host: I've implemented an feature to limit the index by file size so that smaller files such as files can be imported first and large videos can be imported later.

The importer has now following options

```
gallery.js run import

Import and update new files from sources

Options:
      --version         Show version number                            [boolean]
  -l, --log-level       console log level
         [string] [choices: "trace", "debug", "info", "warn", "error", "silent"]
                                                               [default: "info"]
  -L, --log-file        Log file
      --log-file-level  Log file level
         [string] [choices: "trace", "debug", "info", "warn", "error"] [default:
                                                                        "debug"]
  -c, --config          Configuration file       [default: "gallery.config.yml"]
  -i, --initial         Run initial incremental import                 [boolean]
  -u, --update          Check and import new files                     [boolean]
  -s, --small-files     Import only small files up to 20MB to exclude big files
                        such as videos to speed up the initial import  [boolean]
  -h, --help            Show help                                      [boolean]
```

which is available in the newest docker image. So you can append `--small-files` parameter to your initial import.

It is also save to restart the initial setup by deleting the file index files with pattern `*.idx` and the `database.db`. Keep the `events.db` if exists, to keep your manual tags. Than restart the import with `--initial --small-files` parameters. It will reuse the already generated previews from the storage directory - so do not delete that directory ;-)

The result would be a quicker bootstrap of your files. If this step is done you can run the import only with `--initial` parameter to include the larger files, too.
