### ISSUE TITLE
Api server docker container runs on console?

### ISSUE THREAD

**Issue by Qomaa** [xemle/home-gallery#57]
Hi,

when I run the API server docker image, the server is executed in my console and not in background.

```
$ sudo docker run -p 3002:3000 xemle/home-gallery-api-server

Loading tensorflow and models
Load tensorflow width wasm backend in 253ms
Loading model from /app/models/mobilenet-1-100/model.json
Loaded mobilenet model in 1945ms
Loaded faceapi model in 934ms
Loading model from /app/models/coco-ssd-mobilenet_v2/model.json
Loaded coco ssd model in 8434ms
Starting server
Listen on port http://localhost:3000
Setup api routes
Server is up and running

```

How to run the server in background in the docker container? Or is there a different idea behind the API server?

**Comment by xemle** [comment]
You need to run the docker in detached mode with `-d` option, see [docker run help](https://docs.docker.com/engine/reference/run/#detached--d):

```
$ sudo docker run -d -p 3002:3000 xemle/home-gallery-api-server
```

**Comment by Qomaa** [comment]
Thank you! I'm still new to docker.

**Comment by xemle** [comment]
> I'm still new to docker.

That is fine.

I propose to use docker-compose which gives you nicer configuration file
