### ISSUE TITLE
error	"Error: ENOENT: no such file or directory, open '/app/packages/server/dist/public/index.html'"

### ISSUE THREAD

**Issue by Milkysunshine** [xemle/home-gallery#58]
This is the error I'm getting with my docker install. It was working perfectly until recently. Here's the logs:

homegallery_gallery:

cli.run Starting server
cli.task.run Execute: /usr/local/bin/node /app/gallery.js --log-level info --log-file /data/config/gallery.log --log-file-level debug server --storage /data/storage --database /data/config/database.db --events /data/config/events.db
server Open Home Gallery on http://localhost:3000
cli.server Server started. Open it at http://localhost:3000
server.api.database.read Read database file /data/config/database.db with 29685 entries
server.api.events Read events file /data/config/events.db with 1 events
server.webapp error Could not read index file /app/packages/server/dist/public/index.html
server.request warn 404 GET / 21ms

homegallery_api:

Loading tensorflow and models
2022-12-01 15:11:30.996352: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Load tensorflow width node backend in 280ms
Loading model from /app/models/mobilenet-1-100/model.json
Loaded mobilenet model in 349ms
Loaded faceapi model in 332ms
Loading model from /app/models/coco-ssd-mobilenet_v2/model.json
Loaded coco ssd model in 1090ms
Starting server
Listen on port http://localhost:3000
Setup api routes
Server is up and running

Here's my docker_compose.yml:

version: "3.9"
services:
  api:
    # custom build via
    #build: packages/api-server
    image: xemle/home-gallery-api-server
    environment:
      # TensorflowJS backends
      # - cpu: slowest and best support
      # - wasm: good perfromance for arm64 and amd64 platforms
      # - node: best performance on amd64 platform
      #- BACKEND=cpu
      #- BACKEND=wasm
      - BACKEND=node
  gallery:
    # custom build via
    #build: .
    image: xemle/home-gallery
    environment:
      - GALLERY_API_SERVER=http://api:3000
      #- GALLERY_API_SERVER_CONCURRENT=1 # On low powered devices
      #- GALLERY_API_SERVER_TIMEOUT=60 # On low powered devices
      - GALLERY_OPEN_BROWSER=false
    volumes:
      - ./data:/data
      # Mount your media directories below /data
      - /docker/homegallery/data/Pictures:/data/Pictures
    ports:
      - "4000:3000"
    user: "${CURRENT_USER}"
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']

I tried rebuilding, ensuring mounts are fully accessible, etc...

One thing I see in the container itself, is that the /app/packages/server/dist/public directoy doesn't exist. The dir /app/packages/server/dist/ does though.

Thanks in advance for any advice.

**Comment by xemle** [comment]
Hi @Milkysunshine 

Thank you for your report. I was able to reproduce it and pushed v1.8.3 with a bugfix for docker container. Please pull the latest version to receive the fix.

Have fun using HomeGallery

**Comment by Milkysunshine** [comment]
Fix verified working. 

Thanks for your hard work.

Cheers.
