### ISSUE TITLE
Bug: blank image in overview in chrome but not in firefox

### ISSUE THREAD

**Issue by onyxogen** [xemle/home-gallery#59]
Some images  - I could not find out how why - only are shown as a coloured box instead of the preview. Clicking on the preview shows the correct image.
- This happens to me only on Google Chrome but not on firefox.
- only 0.1 % of the images do show this behaviour
- it's not random, fresh import produces the same output

**Comment by xemle** [comment]
Just a lucky guess: It can be caused by an ad blocker, which blocks images in /ad/... directories.

**Comment by onyxogen** [comment]
You nailed it, thx! :1st_place_medal:
