### ISSUE TITLE
Bug: empty tag list and browser cache

### ISSUE THREAD

**Issue by onyxogen** [xemle/home-gallery#60]
Starting a browsing session, e.g. with a bookmark on you launcher, directly to http://xxx.xxx.xxx.xxx:3000/tags shows an empty list, until you switch to "show all" and return back to the tags.

Browser: Chromium / Firefox on android

I also noticed that sometimes to show newly imported pictures you got to delete the browser cache to get the newest state.
I remember from my days of web programming years ago that there is some kind of information on a html page that instructs the browser how to do caching and how long - maybe this could help?

**Comment by xemle** [comment]
I can not reproduce this issue on desktop/mobile with firefox e.g. with https://demo.home-gallery.org/tags

On desktop in a incognito window it opens the tag list and loads the tags.

What settings do you have? What is your mobile device? Do you use user credentials? Dynamic IP?

**Comment by onyxogen** [comment]
I can't reproduce it in firefox, only in chromium based browser like google chrome. 
Meanwhile it just doesn't open the tags page, it just opens my stream. it happens on all my android devices. Right now I use a pixel 7 pro. I don't use credentials or a dynamic IP.
I think all those effects are produced by some kind of caching that firefox does not.

**Comment by xemle** [comment]
Could you remove all website/cache data to eliminate caching issues? I can not reproduce it on Android and Desktop on Chrome visiting https://demo.home-gallery.org/tags

**Comment by onyxogen** [comment]
I can't reproduce it anymore I think - I'll close it for now...
