### ISSUE TITLE
Bug: Gesture swiping in mobile browser 

### ISSUE THREAD

**Issue by onyxogen** [xemle/home-gallery#61]
Swiping between pictures works. But as soon as a video is displayed, the swipe gesture (left / right) is not working anymore. So then you have to click the little arrows. Could you activate swiping on videos too?

**Comment by onyxogen** [comment]
I checked the demo page. On my mobile it works perfect for me.
- video indicator perfectly clear
- number of thumbnails per row seems to be way better (maximum of 4?)
- Gesture support working! YES!

Only thing I noticed that grab and panning with a mouse on a desktop browser seems to be buggy because of the change. Which for me would be ok as mobile power user but I think that's not generally true and only my personal opinion :-)

**Comment by xemle** [comment]
> I checked the demo page. On my mobile it works perfect for me.
> 
>     * video indicator perfectly clear

Super. Thank you for checking

>     * number of thumbnails per row seems to be way better (maximum of 4?)

It was not changed. Do you have lots of portrait mode images? Than the stream algorithm has some drawbacks. Could you describe what is good on the demo page and what is bad on your side (in a separate issue)?

>     * Gesture support working! YES!

Super. Thank you for checking

> Only thing I noticed that grab and panning a photo with a mouse on a desktop browser seems to be buggy, but I did not try that before I think, so I'm not sure if it is associated with the changes. Which for me would be ok as mobile power user but I think that's not generally true and only my personal opinion :-)

To be honest: The panning/zooming never worked well on desktop. I am using the gallery also mainly on mobile. So the focus is more fixing mobile issue as desktop issues.
