### ISSUE TITLE
Feature Request: Customizable preview resolutions

### ISSUE THREAD

**Issue by onyxogen** [xemle/home-gallery#62]
Images in home-gallery are compressed in 5 specific resolutions, videos are also compressed according to specific settings.
However, I have high-resolution devices where I would like to have more resolution to see details better (after calling up the image, so not in the overview), even if it means that a photo needs a little more storage space.
Compared to Google Photos, the images are a bit too poorly resolved for me, or the compression settings are set too conservatively. Therefore you could provide a setting to manipulate the 5 resolution settings.

**Comment by xemle** [comment]
Your main use case is to view the images on desktop in 4k, right?

**Comment by onyxogen** [comment]
No, my use case is zooming into pictures to see some details on mobile phones. On desktops I always mainly view the original photos.
Google photos resizes every photo to 16 MP I think (not the preview but the ones that you open). Even this high resolution is not problematic for downloading on the go. Maybe 10 MP would be enough? 

So to be more specific: I did not know which one of the 5 resolutions gets loaded so I'd like to resize every of them. But if you say that always the biggest resolution gets loaded when clicking on a photo e.g. it would be enough to resize this one.

**Comment by xemle** [comment]
Hi @peter-sc 

The new v1.11.0 is released and supports custom image preview sizes via the `gallery.config.yml`. See [configuration docs](https://docs.home-gallery.org/configuration/index.html#full-configuration):

```
#extractor:
  # Preview image settings
  #image:
  #  previewSizes: [1920, 1280, 800, 320, 128]
  #  previewQuality: 80
```

So if you have a 4K monitor you can customize your gallery to have a proper preview resolution. The gallery uses the best fit for the device.

The new version does not cover the resize on desktop. E.g. on a monitor with Full HD you do not receive the 8k preview. This is still an open issue.

See further changes on v1.11.0 in the [Changelog](https://docs.home-gallery.org/changelog.html)
