### ISSUE TITLE
Small resolution image previews cannot be displayed normally in the browser

### ISSUE THREAD

**Issue by hsa00000** [xemle/home-gallery#66]
I use the command `./gallery run import --initial` and most of the photo previews look fine. However, some small resolution image previews cannot be displayed normally in the browser:

https://user-images.githubusercontent.com/60398736/208910677-74d9f084-eb39-4b19-a222-feb46ba9fc77.mp4

The following ZIP file contains these photos so that you can replicate this issue.
[files.zip](https://github.com/xemle/home-gallery/files/10277843/files.zip)

**Comment by xemle** [comment]
Hi @hsa00000 

Thank you for your issue and the details with video and files. I was able to reproduce it and will soon release a bug fix release.

**Comment by xemle** [comment]
Fixed in 1.8.5
