### ISSUE TITLE
Info panel displays duration for files of type "image"

### ISSUE THREAD

**Issue by MarioSob** [xemle/home-gallery#68]
There is no point to display "duration" field for files of type "image" but HomeAgllery does that with fake value of "00:00".

![Duration](https://user-images.githubusercontent.com/23266722/216941918-4f55650c-fae4-4645-ab4d-9bdcb5014047.png)

**Comment by xemle** [comment]
Hi @MarioSob 

Thank you for your feedback. You are right. Duration is not necessary for images.

I will consider it when I will redesign the detail section. PRs are also welcome.

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
