### ISSUE TITLE
Port number from configuration file is ignored

### ISSUE THREAD

**Issue by MelBourbon** [xemle/home-gallery#69]
When starting the binary with `./home-gallery-latest-linux-x64 run server -c /root/.config/home-gallery/gallery.config.yml` the server starts on standard port 3000 even if `/root/.config/home-gallery/gallery.config.yml` is containing
```
server:
  port: 5555
  host: '0.0.0.0'
```
which is also shown if system configuration is shown with `./home-gallery-latest-linux-x64`

System: Debian

**Comment by xemle** [comment]
Hi @MelBourbon 

Thank you for reaching out. You are true. This comes with v1.9.0 and usage of default options of yargs module and the merge of config parameters.

I need to check how I can resolve that issue. It seems to be tricky.

**Comment by xemle** [comment]
Maybe there is a way but I have to check if this is official: https://github.com/yargs/yargs/issues/513#issuecomment-1419982928

**Comment by xemle** [comment]
Hi @MelBourbon 

I've fixed this issue. You can check and test the [latest master binary](https://dl.home-gallery.org/dist/unstable/latest/). If it is working please close this ticket.
