### ISSUE TITLE
Linux Binary use?

### ISSUE THREAD

**Issue by darrepac** [xemle/home-gallery#7]
Hi

Can you elaborate on the way to use the binary.
I have a headless server:
if I log into ssh and launch the binary, it gets killed when I left. I can use nohup solution...and probably screen in order to come back if needed (?)
If I launch the binary in background, I have no more access to the menu.

Then, once the binary is launched, and I have new photos to scan in my library. Do I have to stop the binary and launch again choosing the right menu etc? without talking about live monitoring, is there a way to cron a scan of the library every night for example?

thanks

**Comment by xemle** [comment]
The binary is [tar.gz from dl.home-gallery.org/dist](https://dl.home-gallery.org/dist/latest) plus the binary wrapper [caxa](https://github.com/leafac/caxa). If you know what you are doing I recommend to use the tar.gz version.

Regarding cron jobs: The binary calls `gallery.js` which is a wrapper around `gallery.config.yml` and `cli.js`. `cli.js` is the older version and `gallery.js` was introduced to simplify common use cases of importing media and starting the server. Both needs to be merged.

When calling `gallery.js` the args for `cli.js` are printed and can be used - until the merge ;-) The next step after that would be to provide a kind of a admin web interface for `gallery.js`. As stated before: It is a question of prioritization and available work power.

Again: Thank you for your valuable input and the discussion.

**Comment by darrepac** [comment]
I ma just using home-gallery-latest-linux-x64 binary

**Comment by xemle** [comment]
`cli.js` and `gallery.js` are now merged on the master including a non-interactive commands through `run` command. See `./gallery.js run -h` (or via docker image):

```
Run common tasks

Commands:
  gallery.js run server  Start the webserver
  gallery.js run import  Import and update new files from sources

Options:
      --version  Show version number                                   [boolean]
  -c, --config   Configuration file              [default: "gallery.config.yml"]
  -h, --help     Show help                                             [boolean]
```

and `./gallery run import -h`:

```
Import and update new files from sources

Options:
      --version  Show version number                                   [boolean]
  -c, --config   Configuration file              [default: "gallery.config.yml"]
  -i, --initial  Run initial incremental import                        [boolean]
  -u, --update   Check and import new files                            [boolean]
  -h, --help     Show help                                             [boolean]
```

@darrepac Does this fits your needs?

**Comment by xemle** [comment]
Version 1.1.0 was released with detailed [installation instruction](https://docs.home-gallery.org/install) for binary installation.

I am closing this ticket.
