### ISSUE TITLE
home-gallery ignores files with capital filename extension

### ISSUE THREAD

**Issue by MelBourbon** [xemle/home-gallery#70]
My camera is creating files where the filename extension is in capital letters `picture.JPG`. These seem to be ignored from home-gallery. I want to avoid to bulk change all of these as these are many. Is there a option to implement that these are not ignored?

**Comment by MelBourbon** [comment]
I now found out that not all `*.JPG*` are ignored and I will net to further check why some are.

**Comment by xemle** [comment]
Hi @MelBourbon glad you find the solution.

Does the exclusion pattern/option requires some clarification?
