### ISSUE TITLE
Is it possible to run 2 instances of home-gallery?

### ISSUE THREAD

**Issue by onyxogen** [xemle/home-gallery#71]
Why: Because I need to implement some kind of "user management"
How: I'd like to run one instance on localhost:3000 and one on localhost:3001

Problem: The second instance doesn't start, even after changing the port in the config.

**Comment by xemle** [comment]
Hi @onyxogen 

What setting are you using? Are you using docker, docker-compose or the binary? The later might have a configuration problem which is fixed in the master, see #69.

**Comment by onyxogen** [comment]
I'm was trying to use the binary 1.9.0, in two directories.
Config 1: 
server:
  port: 3000
  host: '0.0.0.0'

Config 2: 
server:
  port: 3001
  host: '0.0.0.0'

**Comment by xemle** [comment]
@onyxogen Please use the [latest master binary](https://dl.home-gallery.org/dist/unstable/latest/) for it. It should fix your problem

**Comment by onyxogen** [comment]
Thanks, it fixed it!
