### ISSUE TITLE
Provide Arm Binary

### ISSUE THREAD

**Issue by huangyinhaow** [xemle/home-gallery#84]
Now that we have docker builds for arm64, it would be even better to provide pre-built binaries for arm64!

**Comment by xemle** [comment]
Hi @huangyinhaow 

Thank you for your input. What is your motivation to have a pre-build binary for arm64? Which OS and device do you have in mind?

The binaries are build using [caxa](https://github.com/leafac/caxa) as lightweight binary application bundler. It comes without app signing for Windows or Mac - but is great for the start. HomeGallery (bundle package) uses still the version 1.0.0 from caxa which does not support arm64 binaries. Version [2.0.0](https://github.com/leafac/caxa/releases/tag/v2.0.0) of caxa does support arm64.

Up to now none requested the arm64 binary. PRs are welcome. Feel free to dig around in the bundle package, upgrade the caxa dependencies and [bundle.yml](https://github.com/xemle/home-gallery/blob/master/bundle.yml) definition. Do not hesitate to raise questions

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
