### ISSUE TITLE
Q: Latest docker compose enables self hosted similarity search api server by default?

### ISSUE THREAD

**Issue by SimonPae** [xemle/home-gallery#87]
Hey there, I was wondering if I am using the local api server or the public one.
To me it seems, the latest docker compose file  enables the local api server by default. Is this correct?
If so, no need to enable the extractor section in the config. Correct?

<details>

<summary>If so, no need to read the following...</summary>

> My docker compose:
> version: "3.9"
> services:
>   api:
>     # custom build via
>     #build: packages/api-server
>     image: xemle/home-gallery-api-server
>     environment:
>       # TensorflowJS backends
>       # - cpu: slowest and best support
>       # - wasm: good perfromance for arm64 and amd64 platforms
>       # - node: best performance on amd64 platform
>       #- BACKEND=cpu
>       - BACKEND=wasm
>       #- BACKEND=node
>   gallery:
>     # custom build via
>     #build: .
>     image: xemle/home-gallery
>     environment:
>       - GALLERY_API_SERVER=http://api:3000
>       #- GALLERY_API_SERVER_CONCURRENT=1 # On low powered devices
>       #- GALLERY_API_SERVER_TIMEOUT=60 # On low powered devices
>       - GALLERY_OPEN_BROWSER=false
>       # Use polling for safety of possible network mounts. Try 0 to use inotify via fs.watch
>       - GALLERY_WATCH_POLL_INTERVAL=0 #300
>     volumes:
>       - ./data:/data
>       # Mount your media directories below /data
>     ports:
>       - "3000:3000"
>     user: "root"
>     entrypoint: ['node', '/app/gallery.js']
>     command: ['run', 'server']

Further I get the following logs from the api docker service:

> homegallery-api-1  | Loading tensorflow and models
> homegallery-api-1  | Load tensorflow width wasm backend in 209ms
> homegallery-api-1  | Loading model from /app/models/mobilenet-1-100/model.json
> homegallery-api-1  | Loaded mobilenet model in 529ms
> homegallery-api-1  | Loaded faceapi model in 243ms
> homegallery-api-1  | Loading model from /app/models/coco-ssd-mobilenet_v2/model.json
> homegallery-api-1  | Loaded coco ssd model in 1727ms
> homegallery-api-1  | Starting server
> homegallery-api-1  | Listen on port http://localhost:3000
> homegallery-api-1  | Setup api routes
> homegallery-api-1  | Server is up and running
> homegallery-api-1  | Read binary body with 53937 bytes
> homegallery-api-1  | POST /embeddings 200 522.791 ms - 17449
> homegallery-api-1  | Read binary body with 53937 bytes
> homegallery-api-1  | POST /objects 200 1331.503 ms - 1237
> homegallery-api-1  | Read binary body with 53937 bytes
> homegallery-api-1  | POST /faces 200 1955.142 ms - 148

To me it clearly shows, I am using my local similarity api service.
But I just used the default config from [here](https://docs.home-gallery.org/configuration/index.html#configuration)
Which does not enable the extractor section.

On the other hand, in the docker compose section it says:

> By default the wasm backend for the API server is used for best support on most platforms (SoS, NAS, cloud and desktop). Use node backend for best performance on amd64 CPUs like desktops. Please validate that the backend node works for you.

So I am just confused, because in the beginning I just had the docker compose file without the config file and I got the error that the config file is missing. Now I added the config file which does NOT configer the extractor but the api service is defined in the docker compose file.

</details>

**Comment by xemle** [comment]
Hi @SimonPae 

According to the [setup documentation](https://docs.home-gallery.org/install/index.html#id6) you need to setup a configuration file. Otherwise the gallery does not know which directories to import. Short: no config, no gallery.

Second the docker-compose.yml comes with a good default setting and the local api server is configured via environment variable [GALLERY_API_SERVER](https://github.com/xemle/home-gallery/blob/master/docker-compose.yml#L20) and does not need to be set in the config.

So yes, you are using the local api server. Have also a look to the logs: If the public api server is used, than a warning is logged. See https://github.com/xemle/home-gallery/issues/53#issuecomment-1300253030

**Comment by xemle** [comment]
You are welcome. I am happy to help. Enjoy the gallery and your memories
