### ISSUE TITLE
[Bug] search for tags on tags-page finds all search-hits

### ISSUE THREAD

**Issue by joe128** [xemle/home-gallery#90]
If you click on a tag in the listing of tags (../tags), a full search will be performed (../search/"Tag-name").
a search similar to the search for a tag over the detail-page (search/tag:"Tag-name") would limit the results more precisely.

**Comment by xemle** [comment]
Hi @joe128 

Thank you for reaching out. You are right. It would make sense to fix the links in `/tags` to search for `/search/tag:"Tag-name"`. The quotes are only required if the tag has whitespaces eg. `/search/tag:"Tag name"` is preferred.

Would you mind to open a PR?

**Comment by joe128** [comment]
all right, i will create it
