### ISSUE TITLE
Feature: Recent tags buttons directly in the info panel

### ISSUE THREAD

**Issue by pyheme** [xemle/home-gallery#92]
I very recently came across Home Gallery and really like what I'm seeing so far.  The platform looks great and is very responsive. 

As I'm running it for the first time on a rather large amount of pictures, I've been tagging quite a few pictures to classify them but, mainly, to identify those that need to be deleted. 

Adding a tag requires to click on the `edit tags` link, type/click on tags to be added and validate with `Submit` button. 
I was thinking that if the `Recent tags` list that shows up in the `edit tags` window could show up directly in the picture details panel, users could directly apply those tags with a single click. 

It's been (many) years since I've last done anything relevant in JS, so before digging into the code to try to make sense of it and see if I can implement the above idea, I wanted to first ask here how feasible do you think this is?

For info, my use case for Home Gallery is to easily browse media from folders autopopulated with backups of our family's cellphone cameras (using syncthing). Obviously, after years of hording on this data, I have a lot of garbage to comb through, especially in photos, hence the looking for a way to make this as painless as possible.

**Comment by pyheme** [comment]
Sorry... I didn't see the edit button in the menu bar.   This would basically solve my use case.

**Comment by pyheme** [comment]
Hi @xemle, 
Thanks for the response. Yes, the original idea was to add the recent tags as a simple action button near the tag rows where a simple click would add that tag to the photo. 

The multi edit button allows for multiple selection of photos in the gallery view and tagging of these photos in groups. My use case is definitely satisfied this way. I was actually able to clean up most of the photos I wanted deleted in my gallery in a couple of hours today by tagging them through the multi edit tool and then a bash script looking for filenames of these tagged photos and deleting them.

Should we want to pursue with the original idea, though, I do think the overall user experience related to tagging a single photo could be slightly improved by reducing the process to a single click, but to be honest, I'm not convinced it's worth the efforts with the multi tool in place. If a user was to tag a couple of photos, the current process is more than manageable, if there are tens of photos, then they can be done in batch.
With respect to mobile layout, if limited to a 10 or so tags, I think that it could be manageable with some padding/margins in between each tag.

**Comment by xemle** [comment]
@pyheme Thank you for your response and I am happy that the tagging with the multi edit helps you.

I keep direct tagging in my mind for a redesign of the detailed info section.

I could imaging not having a 1-click solution but a 2-click solution via an action "Add recent tags" near the given tags. This action expands a section with recent tags. Clicking on them adds the tag directly. So the UI is not crowded and on mobile tap and swiping there 1-click barrier for false tagging.
