### ISSUE TITLE
Interface translation

### ISSUE THREAD

**Issue by mxm199** [xemle/home-gallery#95]
Good day. Of course, I understand that the interface is minimalistic, and this is very good, but I would like to translate the menu items. Other languages, as I understand it, are not supported out of the box, tell me where the files (web server) containing menu items are located in the container (docker), I want to translate the items directly and then attach this file/files to the container. Thanks!

**Comment by xemle** [comment]
Hi @mxm199 

thank you for reaching out and offer your help.

Localization is currently not supported. Also there is no dedicated language file, too. All text are baked into the webapp, like the [menu](https://github.com/xemle/home-gallery/blob/master/packages/webapp/src/navbar/ViewNavBar.tsx#L58).

PRs are welcome to change that. I guess [i18next](https://react.i18next.com/latest/using-with-hooks) would be awesome to use.
