### ISSUE TITLE
First install on windows with x64 binaries

### ISSUE THREAD

**Issue by gabryk91** [xemle/home-gallery#97]
Hi, I executed the home-gallery-1.13.2-win-x64.exe file and waited it to finish, then I edited the config file and started it again.
It is now in this state:
![image](https://github.com/xemle/home-gallery/assets/9896533/4a947b9b-29ae-4108-a0ef-d969058a9b4b)
And I wonder if all it's fine or if it is stuck, how can I know?

**Comment by xemle** [comment]
Hi @gabryk91 

the binary starts the interactive menue if no argument is given. You can select "Start server" or run the binary with arguments: run server

Choose your preferrence

**Comment by gabryk91** [comment]
Hi thank you, I just discovered that it was a navigable menu and I was coming back here to delete the post hoping no one had read it yet... I was just staring at it waiting something to happen and could have been a loooong wait XD
