### ISSUE TITLE
Random ordering isn't very random

### ISSUE THREAD

**Issue by vityav** [xemle/home-gallery#99]
I've been playing around with `order by random` and finding that, in my tests at least, it's very non-random. Of the first 50 pictures shown of an 80,000 picture gallery, usually 10-15 would be from the same album, and another 10 from another album (with average albums of about 50 pictures each). I could refresh and it would change which albums were shown, but the pictures themselves tended to be highly grouped.

I went down a rabbit hole of javascript sorting algorithms and found that the `0.5 - Math.sort()` method seems to be [questionable](http://www.robweir.com/blog/2010/02/microsoft-random-browser-ballot.html). I tested a number of things including sorting by a filename hashcode combined with a random seed and sorting by crypto.getRandomValues(), none of which worked well until I bypassed the two-element comparison sort entirely. I ended up implementing a [Durstenfeld (Fisher-Yates) Shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm), also described in code [here](https://stackoverflow.com/a/12646864/469653), and that has been working wonderfully. 

The basic idea was to bypass the `orderBy` routine entirely in `src/query/order-by.js`:
```
if (!orderByAst) { 
  return entries  
}  

if (ast.orderBy.value == 'random') {
  return shuffle(entries)  
}  
```

and introduce the shuffle algorithm for the entire thing (note that modifying the array in-place messed with the dynamic sorting going on, so had to make a slice copy):
```
function shuffle(array_init) {
    array=array_init.slice(0)
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array
}
```

It does run a bit slower than the existing random sort, but not by much, and for sorting 80k pictures adding an extra second or two isn't bad.

I'd be happy to submit a PR if that's of interest, or run tests, or just leave it here for reference if anyone comes looking but you don't want to add complexity for something possibly nobody but me uses. In any event, seemed worth sharing.

**Comment by xemle** [comment]
Hi @vityav 

Wow. That is quite deep in the rabbit hole. Awesome. Awesome that you are using HomeGallery and awesome that it bugs you in a quite particularly part of the software. Thank you very much for your proposal.

You describe the the current solution does not help you. Why is the updated version helps you with a better randomization? What are you trying to solve with the random sort order? For me it gives me some random entry points into my gallery if I am in the mood and do not know where to start the exploration.

I am interested in this PR, curious which quality it brings and would like to play around with it. I do have 100k pictures and I would like to know also the performance of it.

It would be also possible to provide an additional sort keyword like `srandom` for 'superior random' if the performance is not good. We will see.

**Comment by vityav** [comment]
I think I have the same use case as you, where I want random entry points into my gallery. Something just bothers me expecting 50 random entries into my life and only getting 10 entries spread across 50 pictures.

I ran some time trials using firefox with cache disabled in a private window closed between runs and was actually surprised to find that the updated random was consistently faster than the existing random:

| trial | random (s) | srandom (s) |
| --- | --- | --- |
| 1 | 15.70 | 13.83 |
| 2 | 16.11 | 13.53 |
| 3 | 15.67 | 13.97 |

That didn't seem to fit with my previous experience so I tried again with caching enabled for the second and third tests:

| trial | random (s) | srandom (s) |
| --- | --- | --- |
| 1 | 15.72 | 13.57 |
| 2* | 15.75 | 13.62 |
| 3* | 15.10 | 13.44 |

And then again in a non-private tab with all of my extensions enabled where I started to notice that something I have set up seems to be doing a better caching job than stock firefox. Note that in this case I added two sets of runs and I ran things in the order `srandom -> random -> srandom test 2 -> random test 2` because it seemed like some amount of caching was carrying over between runs even when I set the profiler to disable caching for the first test of each set.

| trial | random (s) | srandom (s) | srandom test 2 (s) | random test 2 (s) |
| --- | --- | --- | --- | --- |  
| 1 | 12.05 | 14.36 | 10.48 | 11.88 |
| 2* | 11.57 | 11.14 | 10.76 | 10.64 |
| 3* | 11.49 | 10.60 | 9.06 | 11.07 |

All this seems to suggest that maybe the updated algorithm is actually quicker and my initial speed impressions were just biased (either mentally or by caching), and possibly even that the new algorithm improves subsequent random page loads since more of the pictures have been seen/cached in the initial sort? Largely conjecture with such a small specific trial, but promising.

**Comment by xemle** [comment]
Thank you very much for the datailed results. Love that you compare the original with the new implementation.

I want just to verify your numbers: Are the times the loading times in the browser in seconds or are these numbers the time to execute the sorting direct in the query execution in ms?

**Comment by vityav** [comment]
Those were times for loading the page in the browser in seconds. The actual execution time of srandom is crazy low and almost all of the browser load time is from the dynamic loading of images in batches. I just ran it to test though, and made sure the values reported in the logs (e.g. `Found 67834 of 67834 entries by query 'order by srandom' (resolved to 'orderBy(srandom)') in 2ms`) matched a custom timer I added to the `execQuery` function:

| Entries | random (ms) | srandom (ms) |
| --- | --- | --- |
| 969 | 10 | 0 |
| 23548 | 481  | 1 |
| 47514 | 947  | 2 |
| 67834 | 1243 | 3 |

**Comment by xemle** [comment]
Wow. Good job.

You where opening my eys with the random stuff which is not random. Would be happy about a PR

**Comment by xemle** [comment]
Thank you for your input. The new sort algorithm can be tested at the [demo gallery](https://demo.gallery.org)
